(()=>{
const CREDIT_API='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/credits-api';
const STORE_API='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/store-api';
const PACKAGES={starter_500:{id:'starter_500',credits:500,price:5.99},creator_1000:{id:'creator_1000',credits:1000,price:12}};
const TOOLS=[
 {key:'chat',icon:'✦',en:'AI Chat',km:'AI Chat',cost:'1–3 credits/request'},
 {key:'image',icon:'▧',en:'AI Image',km:'AI Image',cost:'10–30 credits/image'},
 {key:'video',icon:'▶',en:'AI Video',km:'AI Video',cost:'150–300+ credits/video'},
 {key:'voice',icon:'♪',en:'AI Voice',km:'AI Voice',cost:'20–40 credits/min'},
 {key:'dubbing',icon:'◎',en:'AI Dubbing',km:'AI Dubbing',cost:'110+ credits/min'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const isKh=()=>localStorage.getItem('nex_prompt_lang')==='KH'||document.documentElement.lang==='km';
const txt=(en,km)=>isKh()?km:en;
const getSession=()=>{try{return JSON.parse(localStorage.getItem('nex_cloud_session')||'null')}catch{return null}};
const setSession=s=>s?localStorage.setItem('nex_cloud_session',JSON.stringify(s)):localStorage.removeItem('nex_cloud_session');
let chosen=null,currentPayment=null,statusTimer=null,countdownTimer=null,checking=false,authMode='signup',activeTool='chat';

function toast(m){const t=$('#toast');if(!t)return alert(m);t.textContent=m;t.classList.add('show');clearTimeout(window.__nexToast);window.__nexToast=setTimeout(()=>t.classList.remove('show'),2800)}
function open(id){const d=document.getElementById(id);if(d&&!d.open){try{d.showModal()}catch{d.setAttribute('open','')}}}
function close(id){const d=document.getElementById(id);if(d?.open){try{d.close()}catch{d.removeAttribute('open')}}}
function safeScroll(s){document.querySelector(s)?.scrollIntoView({behavior:'smooth',block:'start'})}
async function fetchJson(url,options={},timeout=12000){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...options,signal:c.signal});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}catch(e){if(e?.name==='AbortError')throw new Error(txt('Connection timed out.','ការតភ្ជាប់យូរពេក។'));throw e}finally{clearTimeout(tm)}}
const storeRequest=(action,body)=>fetchJson(`${STORE_API}?action=${encodeURIComponent(action)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function creditRequest(action,{method='GET',body}={}){const s=getSession();if(!s?.access_token)return Promise.reject(new Error(txt('Please sign in first.','សូមចូលគណនីជាមុន។')));return fetchJson(`${CREDIT_API}?action=${encodeURIComponent(action)}`,{method,headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:body?JSON.stringify(body):undefined})}

function injectCss(){if($('#nex-member-style'))return;const s=document.createElement('style');s.id='nex-member-style';s.textContent=`
.nex-top-auth{display:flex!important;align-items:center!important;gap:8px!important;position:relative!important;z-index:1000!important}
#loginBtn{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-height:42px!important;padding:0 14px!important;border:1px solid rgba(255,91,162,.45)!important;border-radius:13px!important;background:transparent!important;color:#ff62aa!important;font-weight:850!important;box-shadow:none!important;white-space:nowrap!important;pointer-events:auto!important}
#nexSignupTopBtn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 17px;border:0;border-radius:13px;background:linear-gradient(135deg,#ff258f,#ff61ad);color:white;font-weight:900;box-shadow:0 9px 22px rgba(236,39,130,.22);cursor:pointer;white-space:nowrap}
#nexToolsTopBtn{display:none;align-items:center;justify-content:center;min-height:42px;padding:0 14px;border:1px solid rgba(255,91,162,.32);border-radius:13px;background:rgba(255,47,145,.09);color:#ff62aa;font-weight:850;cursor:pointer;white-space:nowrap}
#authDialog.nex-auth-dialog{width:min(470px,94vw)!important;border:1px solid rgba(255,87,160,.28)!important;border-radius:26px!important;padding:0!important;background:linear-gradient(180deg,#fff,#fff8fc)!important;box-shadow:0 30px 90px rgba(71,18,55,.32)!important;overflow:hidden!important}
#authDialog.nex-auth-dialog::backdrop,#nexToolsDialog::backdrop{background:rgba(16,8,22,.68)!important;backdrop-filter:blur(9px)!important}
.nex-auth-wrap{position:relative;padding:30px}.nex-auth-logo{width:58px;height:58px;border-radius:18px;display:grid;place-items:center;margin:0 auto 14px;background:linear-gradient(145deg,#ff54a4,#ef1f83);color:#fff;font-size:25px}.nex-auth-wrap h2{text-align:center;margin:0;color:#18121a}.nex-auth-sub{text-align:center!important;color:#887a85!important;font-size:12px!important}
.nex-auth-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;padding:5px;border-radius:14px;background:#f8edf3;margin:15px 0}.nex-auth-tab{border:0;border-radius:10px;padding:11px;background:transparent;color:#8e7382;font-weight:800}.nex-auth-tab.active{background:#fff;color:#ed2c86;box-shadow:0 5px 16px rgba(109,54,84,.09)}
.nex-auth-field{margin:9px 0}.nex-auth-field label{display:block;margin-bottom:5px;color:#675963;font-size:11px;font-weight:700}.nex-auth-field input{width:100%;height:47px;border:1px solid #ead8e2;border-radius:13px;padding:0 14px;background:#fff;outline:0;color:#231b22}.nex-pass{position:relative}.nex-pass input{padding-right:50px}.nex-eye{position:absolute;right:7px;top:7px;width:34px;height:34px;border:0;border-radius:9px;background:#fff4f9;cursor:pointer}.nex-auth-submit{width:100%;min-height:49px;margin-top:9px;border:0;border-radius:14px;background:linear-gradient(105deg,#ff258f,#ff62aa);color:#fff;font-weight:900}.nex-auth-status{display:none;margin-top:12px;padding:11px 13px;border-radius:11px;font-size:11px;line-height:1.6}.nex-auth-status.show{display:block}.nex-auth-status[data-type=success]{background:#effcf4;color:#238154}.nex-auth-status[data-type=error]{background:#fff0f1;color:#b83b4e}.nex-auth-logout{display:none;width:100%;margin-top:10px;min-height:43px;border:1px solid #f0cadd;border-radius:13px;background:#fff;color:#c52f75;font-weight:800}
.nex-auth-close,.nex-tool-close{position:absolute!important;right:14px!important;top:12px!important;width:38px!important;height:38px!important;border:1px solid #f3d3e2!important;border-radius:50%!important;background:#fff7fb!important;color:#7a586a!important;font-size:22px!important;z-index:3!important;cursor:pointer!important}
.ai-tool-card{cursor:pointer!important;transition:.2s!important}.ai-tool-card:hover{transform:translateY(-3px)!important}.ai-tool-card.nex-member-open{border-color:rgba(255,73,155,.42)!important}
#nexToolsDialog{width:min(1020px,95vw);max-height:92vh;padding:0;border:1px solid rgba(255,77,156,.28);border-radius:26px;background:linear-gradient(145deg,#110c20,#0b0b18);color:#fff;overflow:auto;box-shadow:0 32px 100px rgba(0,0,0,.55)}
.nex-tools-wrap{position:relative;padding:28px}.nex-tools-head{display:flex;justify-content:space-between;gap:20px;padding-right:48px;margin-bottom:20px}.nex-tools-head h2{margin:4px 0}.nex-tools-head p{margin:0;color:#aaa0b1;font-size:12px}.nex-tools-balance{padding:10px 14px;border:1px solid rgba(255,81,157,.25);border-radius:13px;background:rgba(255,52,144,.07);color:#ff64aa;font-weight:800;height:max-content}
.nex-tools-layout{display:grid;grid-template-columns:240px 1fr;gap:16px}.nex-tools-menu{display:grid;gap:8px;align-content:start}.nex-tool-menu-btn{display:flex;align-items:center;gap:10px;width:100%;padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:13px;background:rgba(255,255,255,.035);color:#d9d2df;text-align:left;cursor:pointer}.nex-tool-menu-btn.active{border-color:rgba(255,75,157,.42);background:rgba(255,49,143,.10);color:#ff65aa}.nex-tool-menu-btn small{display:block;color:#8f8796;font-size:9px}
.nex-tool-panel{min-height:390px;padding:22px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(255,255,255,.03)}.nex-tool-panel-head{display:flex;align-items:center;gap:13px}.nex-tool-panel-icon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(145deg,#ff4fa2,#ec2583);font-size:22px}.nex-tool-panel h3{margin:0;font-size:24px}.nex-tool-panel p{color:#aaa0b1}.nex-tool-cost-pill{display:inline-flex;padding:7px 10px;border:1px solid rgba(255,82,158,.28);border-radius:999px;background:rgba(255,48,143,.07);color:#ff65aa;font-size:10px;font-weight:800}.nex-tool-input{width:100%;min-height:135px;margin-top:14px;padding:14px;border:1px solid rgba(255,255,255,.11);border-radius:14px;background:#0d0c18;color:#fff;resize:vertical}.nex-tool-upload{display:flex;justify-content:space-between;gap:12px;margin:12px 0;padding:12px;border:1px dashed rgba(255,255,255,.15);border-radius:13px;color:#aaa0b1;font-size:11px}.nex-tool-provider-note{margin-top:14px;padding:12px;border:1px solid rgba(255,183,67,.18);border-radius:13px;background:rgba(255,183,67,.06);color:#d6bd8a;font-size:11px}.nex-tool-run{width:100%;min-height:47px;margin-top:14px;border:0;border-radius:14px;background:linear-gradient(105deg,#ff258f,#ff62aa);color:#fff;font-weight:900;opacity:.58;cursor:not-allowed}
@media(max-width:1120px){.top-actions .search{display:none!important}#loginBtn,#nexSignupTopBtn,#nexToolsTopBtn{padding:0 10px!important;font-size:10px!important}}
@media(max-width:760px){.nex-tools-layout{grid-template-columns:1fr}.nex-tools-menu{grid-template-columns:1fr 1fr}.nex-tools-head{display:block}.nex-tools-balance{display:inline-flex;margin-top:10px}.nex-top-auth{margin-left:auto!important}#nexToolsTopBtn{display:none!important}}
`;document.head.appendChild(s)}

function buildAuth(){const d=$('#authDialog');if(!d)return;d.className='nex-auth-dialog';d.innerHTML=`<div class="nex-auth-wrap"><button type="button" class="nex-auth-close" id="nexAuthClose">×</button><div class="nex-auth-logo">▶</div><h2>Nex Prompt</h2><p class="nex-auth-sub" id="nexAuthSub"></p><div class="nex-auth-tabs"><button type="button" class="nex-auth-tab" data-nex-auth="signup"></button><button type="button" class="nex-auth-tab" data-nex-auth="login"></button></div><form id="nexAuthForm"><div class="nex-auth-field" id="nexNameField"><label id="nexNameLabel"></label><input id="nexAuthName" autocomplete="name"></div><div class="nex-auth-field"><label id="nexEmailLabel"></label><input id="nexAuthEmail" type="email" autocomplete="email" required></div><div class="nex-auth-field"><label id="nexPassLabel"></label><div class="nex-pass"><input id="nexAuthPassword" type="password" minlength="6" required><button type="button" class="nex-eye" id="nexAuthEye">👁</button></div></div><button class="nex-auth-submit" id="nexAuthSubmit" type="submit"></button></form><div class="nex-auth-status" id="nexAuthStatus"></div><button type="button" class="nex-auth-logout" id="nexAuthLogout"></button></div>`;$('#nexAuthClose').onclick=()=>close('authDialog');$$('.nex-auth-tab').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.nexAuth));$('#nexAuthEye').onclick=()=>{const p=$('#nexAuthPassword');p.type=p.type==='password'?'text':'password';$('#nexAuthEye').textContent=p.type==='password'?'👁':'🙈'};$('#nexAuthForm').onsubmit=e=>{e.preventDefault();submitAuth()};$('#nexAuthLogout').onclick=()=>{setSession(null);ensureTopAuth();loadBalance();setAuthMode('signup');authStatus(txt('Signed out.','បានចាកចេញពីគណនី។'),'success')};applyAuthLanguage();setAuthMode('signup')}
function authStatus(m,type='info'){const el=$('#nexAuthStatus');if(!el)return;el.textContent=m||'';el.dataset.type=type;el.classList.toggle('show',!!m)}
function setAuthMode(mode,clear=true){authMode=mode==='login'?'login':'signup';$$('.nex-auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.nexAuth===authMode));if($('#nexNameField'))$('#nexNameField').style.display=authMode==='signup'?'block':'none';if($('#nexAuthSubmit'))$('#nexAuthSubmit').textContent=authMode==='signup'?txt('Create account','បង្កើតគណនី'):txt('Sign in','ចូលគណនី');if($('#nexAuthLogout'))$('#nexAuthLogout').style.display=getSession()?.access_token?'block':'none';if(clear)authStatus('')}
function applyAuthLanguage(){if(!$('#nexAuthForm'))return;const signup=$('[data-nex-auth="signup"]'),login=$('[data-nex-auth="login"]');$('#nexAuthSub').textContent=txt('Create an account or sign in to access multiple AI tools.','ចុះឈ្មោះ ឬចូលគណនី ដើម្បីប្រើ AI Tools ច្រើនមុខ។');signup.textContent=txt('Sign up','ចុះឈ្មោះ');login.textContent=txt('Login','ចូល');$('#nexNameLabel').textContent=txt('Display name','ឈ្មោះ');$('#nexEmailLabel').textContent=txt('Email address','អ៊ីមែល');$('#nexPassLabel').textContent=txt('Password','ពាក្យសម្ងាត់');$('#nexAuthLogout').textContent=txt('Sign out','ចាកចេញ');setAuthMode(authMode,false)}
function showAuth(mode='signup'){if(!$('#nexAuthForm'))buildAuth();applyAuthLanguage();setAuthMode(mode);open('authDialog')}
async function submitAuth(){const email=$('#nexAuthEmail').value.trim(),password=$('#nexAuthPassword').value,name=$('#nexAuthName').value.trim(),btn=$('#nexAuthSubmit');if(!email||!password||(authMode==='signup'&&!name))return authStatus(txt('Please complete all fields.','សូមបំពេញព័ត៌មានឲ្យគ្រប់។'),'error');if(password.length<6)return authStatus(txt('Password must be at least 6 characters.','ពាក្យសម្ងាត់ត្រូវមានយ៉ាងហោចណាស់ 6 តួ។'),'error');btn.disabled=true;btn.textContent=txt('Please wait…','សូមរង់ចាំ…');authStatus('');try{if(authMode==='signup'){const d=await storeRequest('signup',{name,email,password});if(d.session){setSession(d.session);ensureTopAuth();await loadBalance();close('authDialog');toast(txt('Account created. Tools unlocked.','បង្កើតគណនីបានជោគជ័យ។ Tools បានបើក។'));safeScroll('#ai-tools')}else authStatus(txt('Confirmation email sent. Confirm it, then sign in.','បានផ្ញើអ៊ីមែលបញ្ជាក់។ សូម Confirm រួចចូលគណនី។'),'success')}else{const d=await storeRequest('signin',{email,password});if(!d.session?.access_token)throw new Error(txt('Could not sign in.','មិនអាចចូលគណនីបាន។'));setSession(d.session);ensureTopAuth();await loadBalance();close('authDialog');toast(txt('Signed in. Tools unlocked.','ចូលគណនីបានជោគជ័យ។ Tools បានបើក។'));safeScroll('#ai-tools')}}catch(e){authStatus(e.message||'Request failed','error')}finally{btn.disabled=false;setAuthMode(authMode,false)}}

function ensureTopAuth(){injectCss();const login=$('#loginBtn'),actions=login?.parentElement;if(!login||!actions)return;let wrap=$('#nexTopAuth');if(!wrap){wrap=document.createElement('div');wrap.id='nexTopAuth';wrap.className='nex-top-auth';actions.insertBefore(wrap,login);wrap.appendChild(login)}let signup=$('#nexSignupTopBtn');if(!signup){signup=document.createElement('button');signup.id='nexSignupTopBtn';signup.type='button';wrap.appendChild(signup)}let tools=$('#nexToolsTopBtn');if(!tools){tools=document.createElement('button');tools.id='nexToolsTopBtn';tools.type='button';wrap.insertBefore(tools,login)}const logged=!!getSession()?.access_token;login.textContent=logged?txt('My Account','គណនី'):txt('Login','ចូល');signup.textContent=txt('Sign up','ចុះឈ្មោះ');signup.style.display=logged?'none':'inline-flex';tools.textContent='✦ Tools';tools.style.display=logged?'inline-flex':'none';login.onclick=e=>{e.preventDefault();showAuth('login')};signup.onclick=e=>{e.preventDefault();showAuth('signup')};tools.onclick=e=>{e.preventDefault();showTools()}}
function authRequired(){if(getSession()?.access_token)return getSession();showAuth('signup');toast(txt('Sign up or login first.','សូមចុះឈ្មោះ ឬចូលគណនីជាមុន។'));return null}

function buildTools(){if($('#nexToolsDialog'))return;const d=document.createElement('dialog');d.id='nexToolsDialog';d.innerHTML=`<div class="nex-tools-wrap"><button class="nex-tool-close" id="nexToolsClose" type="button">×</button><div class="nex-tools-head"><div><small style="color:#ff5fa7;font-weight:900">NEX PROMPT AI</small><h2 id="nexToolsTitle"></h2><p id="nexToolsSub"></p></div><div class="nex-tools-balance" id="nexToolsBalance">0 Credits</div></div><div class="nex-tools-layout"><div class="nex-tools-menu" id="nexToolsMenu"></div><div class="nex-tool-panel" id="nexToolPanel"></div></div></div>`;document.body.appendChild(d);$('#nexToolsClose').onclick=()=>close('nexToolsDialog')}
function renderTools(){buildTools();$('#nexToolsTitle').textContent=txt('Your AI Tools','AI Tools របស់អ្នក');$('#nexToolsSub').textContent=txt('One account gives access to all tools in this workspace.','Account តែមួយ អាចចូលប្រើ Tools ទាំងអស់ក្នុង Workspace នេះ។');$('#nexToolsMenu').innerHTML=TOOLS.map(t=>`<button class="nex-tool-menu-btn ${t.key===activeTool?'active':''}" type="button" data-tool="${t.key}"><span style="font-size:20px">${t.icon}</span><span><b>${isKh()?t.km:t.en}</b><small>${t.cost}</small></span></button>`).join('');$$('#nexToolsMenu [data-tool]').forEach(b=>b.onclick=()=>{activeTool=b.dataset.tool;renderTools()});const t=TOOLS.find(x=>x.key===activeTool)||TOOLS[0],upload=['image','video','dubbing'].includes(t.key);$('#nexToolPanel').innerHTML=`<div class="nex-tool-panel-head"><div class="nex-tool-panel-icon">${t.icon}</div><div><h3>${isKh()?t.km:t.en}</h3><span class="nex-tool-cost-pill">${t.cost}</span></div></div><p>${txt('This tool is available to signed-in members from the same account.','Tool នេះអាចចូលប្រើដោយ Member ដែលបាន Login ក្នុង Account តែមួយ។')}</p><textarea class="nex-tool-input" placeholder="${txt('Enter your prompt or instructions…','សរសេរ Prompt ឬការណែនាំ…')}"></textarea>${upload?`<label class="nex-tool-upload"><span>${txt('Upload source file','បញ្ចូល File ដើម')}</span><input type="file"></label>`:''}<div class="nex-tool-provider-note">${txt('Member access is active. Real AI generation will start after an AI API provider is connected.','Member access បានបើករួច។ ការបង្កើត AI ពិតៗ នឹងដំណើរការបន្ទាប់ពីភ្ជាប់ AI API Provider។')}</div><button class="nex-tool-run" disabled>${txt('AI provider connection required','ត្រូវភ្ជាប់ AI Provider ជាមុន')}</button>`;$('#nexToolsBalance').textContent=$('#creditBalance')?.textContent||'0 Credits'}
function showTools(key){if(!authRequired())return;if(key&&TOOLS.some(t=>t.key===key))activeTool=key;renderTools();open('nexToolsDialog')}
function wireToolCards(){$$('.ai-tool-card').forEach((card,i)=>{const t=TOOLS[i];if(!t)return;card.classList.toggle('nex-member-open',!!getSession()?.access_token);const badge=card.querySelector('.ai-tool-coming');if(badge){badge.textContent=getSession()?.access_token?txt('OPEN TOOL','បើក TOOL'):txt('MEMBERS','MEMBERS')}card.onclick=e=>{e.preventDefault();showTools(t.key)}})}

const formatCredits=n=>Number(n||0).toLocaleString()+' Credits';
async function loadBalance(){const pill=$('#creditBalance');if(!pill)return;if(!getSession()?.access_token){pill.textContent=txt('Sign in','ចូលគណនី');pill.dataset.balance='0';wireToolCards();return}try{const d=await creditRequest('balance');pill.textContent=formatCredits(d.balance);pill.dataset.balance=String(d.balance||0)}catch{pill.textContent=txt('Account','គណនី')}wireToolCards();if($('#nexToolsBalance'))$('#nexToolsBalance').textContent=pill.textContent}
function choosePackage(id){const p=PACKAGES[id];if(!p||!authRequired())return;chosen=p;$('#creditOrderCredits').textContent=formatCredits(p.credits);$('#creditOrderPrice').textContent='$'+p.price.toFixed(2);open('creditDialog')}
function loadQrLib(){if(window.QRCode)return Promise.resolve();return new Promise((resolve,reject)=>{const old=$('#nexQrLib');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.id='nexQrLib';s.src='https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function renderQr(text){const box=$('#creditQr');if(!box)return;box.innerHTML='<div class="credit-spinner"></div>';try{await loadQrLib();box.innerHTML='';new QRCode(box,{text,width:240,height:240,colorDark:'#000',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M})}catch{box.textContent=txt('Could not render QR.','មិនអាចបង្ហាញ QR បាន។')}}
function stopLoops(){if(statusTimer)clearInterval(statusTimer);if(countdownTimer)clearInterval(countdownTimer);statusTimer=countdownTimer=null}
function setStatus(m,type='pending'){const el=$('#creditPayStatus');if(el){el.textContent=m;el.dataset.type=type}}
function updateCountdown(){if(!currentPayment)return;const el=$('#creditPayTimer');if(!el)return;const ms=new Date(currentPayment.expires_at).getTime()-Date.now();if(ms<=0){el.textContent='00:00';setStatus(txt('QR expired.','QR ផុតកំណត់។'),'error');stopLoops();return}const sec=Math.floor(ms/1000);el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function startLoops(){stopLoops();updateCountdown();countdownTimer=setInterval(updateCountdown,1000);statusTimer=setInterval(()=>checkPayment(false),15000)}
function fillPayment(p){currentPayment=p;$('#creditPayAmount').textContent='$'+Number(p.amount_usd).toFixed(2);$('#creditPayCredits').textContent=formatCredits(p.credits);$('#creditSuccessBox')?.classList.remove('show');setStatus(txt('Waiting for payment…','កំពុងរង់ចាំការទូទាត់…'));renderQr(p.qr_string);startLoops()}
async function createPayment(){if(!chosen||!authRequired())return;const b=$('#creditConfirmBtn');if(b)b.disabled=true;try{const d=await creditRequest('create',{method:'POST',body:{package_id:chosen.id}});close('creditDialog');fillPayment(d.payment);open('creditPaymentDialog')}catch(e){toast(e.message)}finally{if(b)b.disabled=false}}
async function checkPayment(manual=true){if(!currentPayment||checking)return;checking=true;try{const d=await creditRequest('status',{method:'POST',body:{client_token:currentPayment.client_token}});if(d.status==='paid'){stopLoops();setStatus(txt('Payment received — credits added ✓','ទូទាត់ជោគជ័យ — Credits បានបញ្ចូល ✓'),'paid');$('#creditSuccessBox')?.classList.add('show');if($('#creditSuccessBalance'))$('#creditSuccessBalance').textContent=formatCredits(d.balance);await loadBalance()}else if(d.status==='expired'){stopLoops();setStatus(txt('QR expired.','QR ផុតកំណត់។'),'error')}}catch(e){if(manual)toast(e.message)}finally{checking=false}}
async function newQr(){if(!chosen&&currentPayment)chosen=PACKAGES[currentPayment.package_id]||{id:currentPayment.package_id,credits:+currentPayment.credits,price:+currentPayment.amount_usd};if(!chosen||!authRequired())return;try{const d=await creditRequest('create',{method:'POST',body:{package_id:chosen.id}});fillPayment(d.payment)}catch(e){toast(e.message)}}

function applyLanguage(){ensureTopAuth();applyAuthLanguage();$$('[data-credit-en]').forEach(el=>{const next=isKh()?el.dataset.creditKm:el.dataset.creditEn;if(next)el.textContent=next});wireToolCards();if($('#nexToolsDialog')?.open)renderTools()}
function wire(){injectCss();buildAuth();buildTools();ensureTopAuth();wireToolCards();$$('[data-credit-package]').forEach(b=>b.onclick=()=>choosePackage(b.dataset.creditPackage));$('#creditConfirmBtn')&&($('#creditConfirmBtn').onclick=createPayment);$('#creditCheckBtn')&&($('#creditCheckBtn').onclick=()=>checkPayment(true));$('#creditNewQrBtn')&&($('#creditNewQrBtn').onclick=newQr);$$('[data-credit-close]').forEach(b=>b.onclick=()=>{stopLoops();close(b.dataset.creditClose)});$('#creditsSide')&&($('#creditsSide').onclick=()=>safeScroll('#credit-plans'));$('#creditWalletBtn')&&($('#creditWalletBtn').onclick=()=>getSession()?.access_token?showTools():showAuth('signup'));$('#langSwitch')?.addEventListener('click',()=>setTimeout(()=>{applyLanguage();loadBalance()},0));window.addEventListener('storage',e=>{if(e.key==='nex_cloud_session'||e.key==='nex_prompt_lang'){applyLanguage();loadBalance()}});applyLanguage();loadBalance();setTimeout(()=>{ensureTopAuth();wireToolCards()},900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
window.NexCredits={loadBalance,choosePackage,showAuth,showTools};
})();