(function(){
'use strict';
var AI='/api/chat';
var REFRESH='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/auth-refresh';
var messages=[];
var sending=false;
function $(s){return document.querySelector(s)}
function isKH(){return localStorage.getItem('nex_prompt_lang')==='KH'}
function getSession(){try{return JSON.parse(localStorage.getItem('nex_cloud_session')||'null')}catch(e){return null}}
function saveSession(s){try{if(s)localStorage.setItem('nex_cloud_session',JSON.stringify(s));else localStorage.removeItem('nex_cloud_session')}catch(e){}}
function refreshSession(){var current=getSession();if(!current||!current.refresh_token)return Promise.reject(new Error('Session expired.'));return fetch(REFRESH,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:current.refresh_token})}).then(function(r){return r.json().catch(function(){return{}}).then(function(d){if(!r.ok||!d.session||!d.session.access_token)throw new Error(d.error||'Session expired.');if(!d.session.email&&current.email)d.session.email=current.email;saveSession(d.session);return d.session})})}
function apiCall(payload,canRefresh){var s=getSession();if(!s||!s.access_token)return Promise.reject(new Error('SIGN_IN_REQUIRED'));return fetch(AI,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.access_token},body:JSON.stringify(payload)}).then(function(r){return r.json().catch(function(){return{}}).then(function(d){if(r.status===401&&canRefresh!==false&&s.refresh_token)return refreshSession().then(function(){return apiCall(payload,false)});if(!r.ok){var e=new Error(d.error||'AI request failed.');e.code=d.code||String(r.status);throw e}return d})})}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function ensureUI(){var d=$('#aiChatModal');if(d)return d;d=document.createElement('dialog');d.id='aiChatModal';d.className='ai-chat-modal';d.innerHTML='<div class="ai-chat-shell"><div class="ai-chat-top"><div><div class="ai-chat-brand">✦ NEXORA Ai</div><h2>AI Chat</h2></div><div class="ai-chat-top-actions"><span id="aiChatFree">FREE</span><button id="aiChatNew" type="button">New chat</button><button id="aiChatClose" type="button">×</button></div></div><div id="aiChatMessages" class="ai-chat-messages"></div><div class="ai-chat-composer"><textarea id="aiChatInput" rows="2" placeholder="Ask NEXORA Ai anything..."></textarea><div class="ai-chat-compose-row"><span id="aiChatHint">FREE · No Credits required</span><button id="aiChatSend" type="button">Send ✦</button></div></div></div>';
document.body.appendChild(d);
var st=document.createElement('style');st.textContent='.ai-chat-modal{padding:0;border:0;background:transparent;max-width:none}.ai-chat-modal::backdrop{background:rgba(3,2,8,.82);backdrop-filter:blur(10px)}.ai-chat-shell{width:min(94vw,980px);height:min(88vh,760px);display:grid;grid-template-rows:auto 1fr auto;overflow:hidden;border:1px solid #5b2a50;border-radius:26px;background:linear-gradient(160deg,#100b17,#08070e);box-shadow:0 35px 110px rgba(0,0,0,.65);color:#fff}.ai-chat-top{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:20px 22px;border-bottom:1px solid #2d1c30}.ai-chat-top h2{margin:3px 0 0;font-size:25px}.ai-chat-brand{font-size:11px;font-weight:900;letter-spacing:.08em;color:#ff69b3}.ai-chat-top-actions{display:flex;align-items:center;gap:9px}.ai-chat-top-actions span,.ai-chat-top-actions button{height:40px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #55304e;border-radius:12px;background:#15101b;color:#f8eef6;padding:0 13px;font-weight:800}.ai-chat-top-actions span{color:#72f2b0;border-color:#28543e;background:#10251b}.ai-chat-top-actions button{cursor:pointer}.ai-chat-top-actions #aiChatClose{width:40px;padding:0;font-size:23px}.ai-chat-messages{overflow:auto;padding:24px;display:flex;flex-direction:column;gap:14px}.ai-chat-empty{margin:auto;max-width:520px;text-align:center;color:#b4a8b5;line-height:1.7}.ai-chat-empty strong{display:block;color:#fff;font-size:28px;margin-bottom:8px}.ai-msg{max-width:82%;padding:13px 15px;border-radius:16px;line-height:1.65;white-space:pre-wrap;word-break:break-word}.ai-msg.user{align-self:flex-end;background:linear-gradient(135deg,#e92c8a,#a64ae8);color:white}.ai-msg.assistant{align-self:flex-start;background:#17111d;border:1px solid #37223a;color:#f3edf3}.ai-msg.loading{opacity:.7}.ai-chat-composer{padding:16px 20px 20px;border-top:1px solid #2d1c30;background:#0d0912}.ai-chat-composer textarea{width:100%;min-height:70px;max-height:180px;resize:vertical;padding:14px 15px;border:1px solid #53304f;border-radius:15px;background:#08070d;color:#fff;font:inherit;outline:none}.ai-chat-composer textarea:focus{border-color:#ff4fa6;box-shadow:0 0 0 3px rgba(255,79,166,.1)}.ai-chat-compose-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:10px}.ai-chat-compose-row span{font-size:11px;color:#72f2b0;font-weight:800}.ai-chat-compose-row button{height:44px;min-width:118px;border:0;border-radius:13px;background:linear-gradient(135deg,#ff3196,#ad4cf0);color:#fff;font-weight:900;cursor:pointer}.ai-chat-compose-row button:disabled{opacity:.55;cursor:not-allowed}@media(max-width:640px){.ai-chat-shell{width:100vw;height:100dvh;border-radius:0}.ai-chat-top{padding:14px}.ai-chat-messages{padding:16px}.ai-msg{max-width:92%}.ai-chat-composer{padding:12px}.ai-chat-compose-row span{font-size:10px}}';document.head.appendChild(st);
$('#aiChatClose').addEventListener('click',function(){try{d.close()}catch(e){d.removeAttribute('open')}});
$('#aiChatNew').addEventListener('click',function(){messages=[];render()});
$('#aiChatSend').addEventListener('click',send);
$('#aiChatInput').addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
d.addEventListener('click',function(e){if(e.target===d){try{d.close()}catch(err){d.removeAttribute('open')}}});
render();return d}
function render(){ensureUI();var box=$('#aiChatMessages');if(!box)return;if(!messages.length){box.innerHTML='<div class="ai-chat-empty"><strong>✦ AI Chat · FREE</strong>'+(isKH()?'សរសេរសំណួរ ឬការងារដែលអ្នកចង់ឲ្យ NEXORA Ai ជួយ។ AI Chat នេះឥតគិតថ្លៃ និងមិនកាត់ Credits ទេ។':'Ask, write, summarize or brainstorm with NEXORA Ai. AI Chat is free and does not use Credits.')+'</div>';return}box.innerHTML=messages.map(function(m){return '<div class="ai-msg '+(m.role==='user'?'user':'assistant')+'">'+esc(m.content)+'</div>'}).join('')+(sending?'<div class="ai-msg assistant loading">'+(isKH()?'NEXORA Ai កំពុងគិត…':'NEXORA Ai is thinking…')+'</div>':'');box.scrollTop=box.scrollHeight}
function openChat(){var s=getSession();if(!s||!s.access_token){var sign=$('#signInBtn');if(sign)sign.click();return}var d=ensureUI();render();try{if(!d.open)d.showModal()}catch(e){d.setAttribute('open','')}setTimeout(function(){var i=$('#aiChatInput');if(i)i.focus()},80)}
function send(){if(sending)return;var input=$('#aiChatInput');var text=String(input&&input.value||'').trim();if(!text)return;messages.push({role:'user',content:text});if(input)input.value='';sending=true;render();var btn=$('#aiChatSend');if(btn)btn.disabled=true;apiCall({messages:messages},true).then(function(d){messages.push({role:'assistant',content:String(d.text||'')})}).catch(function(err){if(err.message==='SIGN_IN_REQUIRED'){var sign=$('#signInBtn');if(sign)sign.click();return}messages.push({role:'assistant',content:isKH()?'AI Chat មិនអាចឆ្លើយបានឥឡូវនេះ។ សូមសាកម្តងទៀត។':String(err.message||'AI service is unavailable. Please try again.')})}).finally(function(){sending=false;if(btn)btn.disabled=false;render()})}
document.addEventListener('click',function(e){var card=e.target.closest('[data-tool="AI Chat"]');if(!card)return;e.preventDefault();e.stopImmediatePropagation();openChat()},true);
})();