(()=>{
'use strict';
const STORE='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/store-api';
const CREDIT='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/credits-api';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fallback=[
{id:'f1',title:'Cinematic Road Reveal',category:'cinematic',creator:'Nex Prompt',model:'Kling / Veo',price:2.49,image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80'},
{id:'f2',title:'Ocean Orbit Motion',category:'nature',creator:'Nex Prompt',model:'Veo',price:2.29,image:'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=900&q=80'},
{id:'f3',title:'Neon City Push In',category:'sci-fi',creator:'Nex Prompt',model:'Kling',price:2.99,image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80'},
{id:'f4',title:'Beach Sunrise Drift',category:'nature',creator:'Nex Prompt',model:'Veo',price:1.99,image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80'}
];
const state={lang:localStorage.getItem('nex_prompt_lang')==='KH'?'KH':'EN',session:read('nex_cloud_session'),cart:read('nex_cart_cloud')||[],catalog:[],filter:'all',authMode:'signup',selectedPrompt:null,creditPack:null,payment:null,poll:null};
const T={
Home:['Home','ទំព័រដើម'],Prompt:['Prompt','Prompt'],'AI Tools':['AI Tools','AI Tools'],Credits:['Credits','Credits'],'How it works':['How it works','របៀបប្រើ'],
'Sign in':['Sign in','ចូល'],'Sign up':['Sign up','ចុះឈ្មោះ'],'Search prompts...':['Search prompts...','ស្វែងរក Prompt...'],
'Explore Prompts':['Explore Prompts','មើល Prompt'],'Premium prompts for creators who want smoother motion, better camera direction and faster AI-video results.':['Premium prompts for creators who want smoother motion, better camera direction and faster AI-video results.','Prompt គុណភាពខ្ពស់ សម្រាប់ Creator ដែលចង់បានចលនារលូន កាមេរ៉ាល្អ និងលទ្ធផល AI Video លឿន។'],
'Prompt Marketplace':['Prompt Marketplace','ទីផ្សារ Prompt'],'AI Tools Workspace':['AI Tools Workspace','AI Tools Workspace'],'Shared Credit Wallet':['Shared Credit Wallet','Credit Wallet រួម'],
'Buy credits':['Buy credits','ទិញ Credits'],'Create account':['Create account','បង្កើតគណនី'],'Email address':['Email address','អ៊ីមែល'],'Display name':['Display name','ឈ្មោះ'],'Password':['Password','ពាក្យសម្ងាត់'],
'Your Cart':['Your Cart','កន្ត្រកទិញ'],'Checkout':['Checkout','ទូទាត់'],'Close':['Close','បិទ'],'Check payment':['Check payment','ពិនិត្យការទូទាត់'],'Waiting for payment…':['Waiting for payment…','កំពុងរង់ចាំការទូទាត់…']};
function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function save(k,v){if(v==null)localStorage.removeItem(k);else localStorage.setItem(k,JSON.stringify(v))}
function tr(k){return T[k]?.[state.lang==='KH'?1:0]||k}
function toast(m){const el=$('#toast');el.textContent=m;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2400)}
function openModal(id){const d=$(id);if(!d)return;try{if(!d.open)d.showModal()}catch{d.setAttribute('open','')}}
function closeModal(id){const d=$(id);if(!d)return;try{if(d.open)d.close()}catch{d.removeAttribute('open')}}
async function request(url,action,{method='GET',body,auth=false,timeout=12000}={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);const headers={'Content-Type':'application/json'};if(auth&&state.session?.access_token)headers.Authorization='Bearer '+state.session.access_token;try{const r=await fetch(`${url}?action=${encodeURIComponent(action)}`,{method,headers,body:body?JSON.stringify(body):undefined,signal:c.signal});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}finally{clearTimeout(timer)}}
function route(name){const v=name==='how'?'home':name;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===name||(name==='how'&&a.dataset.route==='how')));if(name==='prompt')renderPrompts();if(name==='credits')refreshBalance();history.replaceState(null,'','#'+name);if(name==='how')setTimeout(()=>$('#howSection')?.scrollIntoView({behavior:'smooth'}),30);else window.scrollTo({top:0,behavior:'smooth'})}
function applyLanguage(){document.documentElement.lang=state.lang==='KH'?'km':'en';$$('[data-t]').forEach(el=>{el.textContent=tr(el.dataset.t)});$('#searchInput').placeholder=tr('Search prompts...');$$('.lang button').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));renderAuth();renderCart();renderPrompts();updateAuthButtons()}
function updateAuthButtons(){const logged=!!state.session?.access_token;$('#signInBtn').textContent=logged?(state.session?.profile?.display_name||state.session?.email||tr('Sign in')):tr('Sign in');$('#signUpBtn').style.display=logged?'none':'inline-flex';$('#signInBtn').dataset.mode=logged?'account':'signin';$('#walletBalance').textContent=logged?($('#walletBalance').dataset.balance||'0 Credits'):tr('Sign in')}
function renderAuth(){const signup=state.authMode==='signup';$('#authTitle').textContent=signup?tr('Create account'):tr('Sign in');$('#authNameWrap').style.display=signup?'block':'none';$('#authSubmit').textContent=signup?tr('Create account'):tr('Sign in');$$('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.authMode));$('#authStatus').className='status';$('#authStatus').textContent=''}
function showAuth(mode){state.authMode=mode;renderAuth();openModal('#authModal')}
function authStatus(m,type='error'){const el=$('#authStatus');el.textContent=m;el.className='status show '+type}
async function submitAuth(e){e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();if(!email||!password||(state.authMode==='signup'&&!name))return authStatus(state.lang==='KH'?'សូមបំពេញព័ត៌មានឲ្យគ្រប់។':'Please complete all fields.');if(password.length<6)return authStatus(state.lang==='KH'?'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងហោចណាស់ 6 តួ។':'Password must be at least 6 characters.');const btn=$('#authSubmit');btn.disabled=true;try{const d=await request(STORE,state.authMode==='signup'?'signup':'signin',{method:'POST',body:state.authMode==='signup'?{name,email,password}:{email,password}});if(d.session?.access_token){state.session=d.session;state.session.email=email;save('nex_cloud_session',state.session);closeModal('#authModal');updateAuthButtons();refreshBalance();toast(state.lang==='KH'?'ចូលគណនីបានជោគជ័យ។':'Signed in successfully.')}else if(state.authMode==='signup')authStatus(state.lang==='KH'?'បានផ្ញើអ៊ីមែលបញ្ជាក់។ សូម Confirm រួចចូលគណនី។':'Confirmation email sent. Confirm it, then sign in.','success');else authStatus('Could not sign in.')}catch(err){authStatus(err.message||'Request failed')}finally{btn.disabled=false}}
function signOut(){state.session=null;save('nex_cloud_session',null);updateAuthButtons();closeModal('#authModal');toast(state.lang==='KH'?'បានចាកចេញពីគណនី។':'Signed out.')}
function mapPrompt(p){return{id:String(p.id),title:p.title||'Untitled Prompt',category:p.category||'cinematic',creator:p.creator||'Nex Prompt',model:p.model||'',price:Number(p.price||0),image:p.image_url||p.image||''}}
async function loadCatalog(){try{const d=await request(STORE,'catalog',{timeout:9000});state.catalog=(d.items||[]).map(mapPrompt);if(!state.catalog.length)state.catalog=fallback}catch{state.catalog=fallback}renderPrompts()}
function filtered(){const q=($('#searchInput').value||'').toLowerCase().trim();return state.catalog.filter(p=>(state.filter==='all'||p.category===state.filter)&&(!q||`${p.title} ${p.creator} ${p.model} ${p.category}`.toLowerCase().includes(q)))}
function renderPrompts(){const g=$('#promptGrid');if(!g)return;g.innerHTML=filtered().map(p=>`<article class="prompt-card" data-prompt="${p.id}"><div class="prompt-img" style="background-image:url('${escapeAttr(p.image)}')"><span class="prompt-tag">${escapeHtml(p.category)}</span></div><div class="prompt-body"><h3>${escapeHtml(p.title)}</h3><div class="prompt-meta"><span>@ ${escapeHtml(p.creator)}</span><span class="price">$${p.price.toFixed(2)}</span></div><div class="prompt-meta" style="margin-top:8px"><span>${escapeHtml(p.model)}</span><span>View</span></div></div></article>`).join('')||`<div class="empty">${state.lang==='KH'?'រកមិនឃើញ Prompt ទេ។':'No prompts found.'}</div>`}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s=''){return escapeHtml(s)}
function openPrompt(id){const p=state.catalog.find(x=>x.id===String(id));if(!p)return;state.selectedPrompt=p;$('#promptPreview').style.backgroundImage=`url('${p.image}')`;$('#promptTitle').textContent=p.title;$('#promptDesc').textContent=`${p.category} · ${p.model} · @${p.creator}`;$('#promptPrice').textContent='$'+p.price.toFixed(2);$('#addCartBtn').textContent=state.cart.includes(p.id)?(state.lang==='KH'?'មានក្នុងកន្ត្រក':'In Cart'):(state.lang==='KH'?'បន្ថែមទៅកន្ត្រក':'Add to Cart');openModal('#promptModal')}
function addCart(){const p=state.selectedPrompt;if(!p)return;if(!state.cart.includes(p.id))state.cart.push(p.id);save('nex_cart_cloud',state.cart);updateCartCount();$('#addCartBtn').textContent=state.lang==='KH'?'មានក្នុងកន្ត្រក':'In Cart';toast(state.lang==='KH'?'បានបន្ថែមទៅកន្ត្រក។':'Added to cart.')}
function updateCartCount(){$('#cartCount').textContent=state.cart.length}
function renderCart(){const rows=state.cart.map(id=>state.catalog.find(p=>p.id===id)).filter(Boolean);$('#cartItems').innerHTML=rows.map(p=>`<div class="cart-row"><div class="thumb" style="background-image:url('${escapeAttr(p.image)}')"></div><div><b>${escapeHtml(p.title)}</b><div class="price">$${p.price.toFixed(2)}</div></div><button class="remove" data-remove="${p.id}">Remove</button></div>`).join('')||`<div class="empty">${state.lang==='KH'?'កន្ត្រកទទេ។':'Your cart is empty.'}</div>`;$('#cartTotal').textContent='$'+rows.reduce((n,p)=>n+p.price,0).toFixed(2)}
async function promptCheckout(){if(!state.cart.length)return toast(state.lang==='KH'?'កន្ត្រកទទេ។':'Your cart is empty.');const btn=$('#checkoutPromptBtn');btn.disabled=true;try{const d=await request(STORE,'bakong-create',{method:'POST',body:{prompt_ids:state.cart.map(Number)}});state.payment={...d.payment,type:'prompt'};showPayment(d.payment)}catch(err){toast(err.message||'Could not create KHQR')}finally{btn.disabled=false}}
function ensureLogin(){if(state.session?.access_token)return true;showAuth('signup');toast(state.lang==='KH'?'សូមចុះឈ្មោះ ឬចូលគណនីជាមុន។':'Please sign up or sign in first.');return false}
function openTool(name){if(!ensureLogin())return;$('#toolWorkspaceTitle').textContent=name;$('#toolWorkspaceText').textContent=state.lang==='KH'?'Account របស់អ្នកអាចប្រើ Tool នេះបាន។ ការបង្កើត AI ពិតៗ នឹងដំណើរការបន្ទាប់ពីភ្ជាប់ AI Provider។':'Your account can access this tool. Real AI generation will work after an AI provider is connected.';openModal('#toolModal')}
async function refreshBalance(){if(!state.session?.access_token){$('#walletBalance').dataset.balance='';updateAuthButtons();return}try{const d=await request(CREDIT,'balance',{auth:true,timeout:8000});const val=`${Number(d.balance||0).toLocaleString()} Credits`;$('#walletBalance').dataset.balance=val;$('#walletBalance').textContent=val}catch{$('#walletBalance').dataset.balance='0 Credits';$('#walletBalance').textContent='0 Credits'}}
async function buyCredits(id,credits,price){if(!ensureLogin())return;state.creditPack={id,credits,price};const btn=$(`[data-buy="${id}"]`);if(btn)btn.disabled=true;try{const d=await request(CREDIT,'create',{method:'POST',auth:true,body:{package_id:id}});state.payment={...d.payment,type:'credit'};showPayment(d.payment)}catch(err){toast(err.message||'Could not create KHQR')}finally{if(btn)btn.disabled=false}}
function showPayment(p){closeModal('#cartModal');$('#payTitle').textContent=p.credits?`${p.credits} Credits`:(state.lang==='KH'?'ទូទាត់ Prompt':'Prompt payment');$('#payAmount').textContent='$'+Number(p.amount_usd||p.amount||state.creditPack?.price||0).toFixed(2);$('#payStatus').textContent=tr('Waiting for payment…');renderQR(p.qr_string||'');openModal('#paymentModal');startPaymentPoll()}
function renderQR(text){const box=$('#qrBox');box.innerHTML='';try{if(window.QRCode)new QRCode(box,{text,width:206,height:206,correctLevel:QRCode.CorrectLevel.M});else box.innerHTML='<small style="color:#111;word-break:break-all">'+escapeHtml(text)+'</small>'}catch{box.innerHTML='<small style="color:#111;word-break:break-all">'+escapeHtml(text)+'</small>'}}
function startPaymentPoll(){clearInterval(state.poll);state.poll=setInterval(()=>checkPayment(false),15000)}
async function checkPayment(manual=true){if(!state.payment?.client_token)return;try{let d;if(state.payment.type==='credit')d=await request(CREDIT,'status',{method:'POST',auth:true,body:{client_token:state.payment.client_token}});else d=await request(STORE,'bakong-status',{method:'POST',body:{client_token:state.payment.client_token}});if(d.status==='paid'){clearInterval(state.poll);$('#payStatus').textContent=state.lang==='KH'?'✓ ទូទាត់ជោគជ័យ':'✓ Payment confirmed';if(state.payment.type==='credit')await refreshBalance();else{state.cart=[];save('nex_cart_cloud',state.cart);updateCartCount()}toast(state.lang==='KH'?'ការទូទាត់បានជោគជ័យ។':'Payment confirmed.')}else if(d.status==='expired'){$('#payStatus').textContent=state.lang==='KH'?'QR ផុតកំណត់។':'QR expired.'}else if(manual)toast(state.lang==='KH'?'មិនទាន់ទទួលការទូទាត់។':'Payment not received yet.')}catch(err){if(manual)toast(err.message||'Could not check payment')}}
function bind(){
$$('[data-route]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();route(a.dataset.route)}));
$$('.lang button').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.lang;localStorage.setItem('nex_prompt_lang',state.lang);applyLanguage()}));
$('#signUpBtn').addEventListener('click',()=>showAuth('signup'));$('#signInBtn').addEventListener('click',()=>state.session?.access_token?showAuth('login'):showAuth('login'));
$$('.auth-tab').forEach(b=>b.addEventListener('click',()=>{state.authMode=b.dataset.mode;renderAuth()}));$('#authForm').addEventListener('submit',submitAuth);$('#signOutBtn').addEventListener('click',signOut);
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
$('#searchInput').addEventListener('input',()=>{if(!$('#promptView').classList.contains('active'))route('prompt');renderPrompts()});
$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();route('prompt')}});
$('#promptFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderPrompts()});
$('#promptGrid').addEventListener('click',e=>{const c=e.target.closest('[data-prompt]');if(c)openPrompt(c.dataset.prompt)});$('#addCartBtn').addEventListener('click',addCart);
$('#cartBtn').addEventListener('click',()=>{renderCart();openModal('#cartModal')});$('#cartItems').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;state.cart=state.cart.filter(x=>x!==b.dataset.remove);save('nex_cart_cloud',state.cart);updateCartCount();renderCart()});$('#checkoutPromptBtn').addEventListener('click',promptCheckout);
$$('[data-tool]').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.tool)));$$('[data-buy]').forEach(b=>b.addEventListener('click',()=>buyCredits(b.dataset.buy,Number(b.dataset.credits),Number(b.dataset.price))));
$('#walletBalance').addEventListener('click',()=>state.session?.access_token?route('credits'):showAuth('signup'));$('#checkPaymentBtn').addEventListener('click',()=>checkPayment(true));
window.addEventListener('hashchange',()=>{const h=location.hash.replace('#','');if(['home','prompt','tools','credits','how'].includes(h))route(h)});
}
function init(){bind();updateCartCount();applyLanguage();const h=location.hash.replace('#','');route(['home','prompt','tools','credits','how'].includes(h)?h:'home');loadCatalog();refreshBalance()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();