(function(){
'use strict';
var STORE='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/store-api';
var CREDIT='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/credits-api';
function $(s){return document.querySelector(s)}
function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch(e){return null}}
function save(k,v){if(v===null||typeof v==='undefined')localStorage.removeItem(k);else localStorage.setItem(k,JSON.stringify(v))}
var oldCart=read('nex_cart_cloud');
var oldSession=read('nex_cloud_session');
var state={lang:localStorage.getItem('nex_prompt_lang')==='KH'?'KH':'EN',session:oldSession&&typeof oldSession==='object'?oldSession:null,cart:Array.isArray(oldCart)?oldCart.map(String):[],catalog:[],filter:'all',authMode:'signup',selectedPrompt:null,creditPack:null,payment:null,poll:null};
var fallback=[
{id:'f1',title:'Cinematic Road Reveal',category:'cinematic',creator:'Nex Prompt',model:'Kling / Veo',price:2.49,image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80'},
{id:'f2',title:'Ocean Orbit Motion',category:'nature',creator:'Nex Prompt',model:'Veo',price:2.29,image:'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=900&q=80'},
{id:'f3',title:'Neon City Push In',category:'sci-fi',creator:'Nex Prompt',model:'Kling',price:2.99,image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80'},
{id:'f4',title:'Beach Sunrise Drift',category:'nature',creator:'Nex Prompt',model:'Veo',price:1.99,image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80'}
];
var T={Home:['Home','ទំព័រដើម'],Prompt:['Prompt','Prompt'],'AI Tools':['AI Tools','AI Tools'],Credits:['Credits','Credits'],'How it works':['How it works','របៀបប្រើ'],'Sign in':['Sign in','ចូល'],'Sign up':['Sign up','ចុះឈ្មោះ'],'Search prompts...':['Search prompts...','ស្វែងរក Prompt...'],'Create account':['Create account','បង្កើតគណនី'],'Display name':['Display name','ឈ្មោះ'],'Email address':['Email address','អ៊ីមែល'],Password:['Password','ពាក្យសម្ងាត់'],'Your Cart':['Your Cart','កន្ត្រកទិញ'],Checkout:['Checkout','ទូទាត់'],'Check payment':['Check payment','ពិនិត្យការទូទាត់']};
function tr(k){var a=T[k];return a?a[state.lang==='KH'?1:0]:k}
function on(sel,event,fn){var el=$(sel);if(el)el.addEventListener(event,fn);return el}
function toast(m){var el=$('#toast');if(!el)return;el.textContent=m;el.classList.add('show');clearTimeout(window.__nexToast);window.__nexToast=setTimeout(function(){el.classList.remove('show')},2400)}
function openModal(sel){var d=$(sel);if(!d)return;try{if(!d.open)d.showModal()}catch(e){d.setAttribute('open','')}}
function closeModal(sel){var d=$(sel);if(!d)return;try{if(d.open)d.close()}catch(e){d.removeAttribute('open')}}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function request(url,action,opt){opt=opt||{};var ctrl=new AbortController();var timer=setTimeout(function(){ctrl.abort()},opt.timeout||12000);var headers={'Content-Type':'application/json'};if(opt.auth&&state.session&&state.session.access_token)headers.Authorization='Bearer '+state.session.access_token;return fetch(url+'?action='+encodeURIComponent(action),{method:opt.method||'GET',headers:headers,body:opt.body?JSON.stringify(opt.body):undefined,signal:ctrl.signal}).then(function(r){return r.text().then(function(t){var d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.error||'Request failed');return d})}).finally(function(){clearTimeout(timer)})}
function route(name){var view=name==='how'?'home':name;$$('.view').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-view')===view)});$$('[data-route]').forEach(function(a){if(a.closest('.nav'))a.classList.toggle('active',a.getAttribute('data-route')===name)});if(name==='prompt')renderPrompts();if(name==='credits')refreshBalance();try{history.replaceState(null,'','#'+name)}catch(e){}if(name==='how')setTimeout(function(){var h=$('#howSection');if(h)h.scrollIntoView({behavior:'smooth',block:'start'})},20);else window.scrollTo(0,0)}
function updateAuthButtons(){var logged=!!(state.session&&state.session.access_token);var si=$('#signInBtn'),su=$('#signUpBtn'),wb=$('#walletBalance'),cp=$('#creditPageBalance');if(si)si.textContent=logged?(state.session.profile&&state.session.profile.display_name||state.session.email||'Account'):tr('Sign in');if(su)su.style.display=logged?'none':'inline-flex';var bal=(wb&&wb.getAttribute('data-balance'))||'0 Credits';if(wb)wb.textContent=logged?bal:tr('Sign in');if(cp)cp.textContent=logged?bal:'Shared Wallet';var so=$('#signOutBtn');if(so)so.style.display=logged?'block':'none'}
function renderAuth(){var signup=state.authMode==='signup';var t=$('#authTitle'),w=$('#authNameWrap'),s=$('#authSubmit'),st=$('#authStatus');if(t)t.textContent=signup?tr('Create account'):tr('Sign in');if(w)w.style.display=signup?'block':'none';if(s)s.textContent=signup?tr('Create account'):tr('Sign in');$$('.auth-tab').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-mode')===state.authMode)});if(st){st.className='status';st.textContent=''}}
function showAuth(mode){state.authMode=mode==='signin'?'signin':'signup';renderAuth();openModal('#authModal')}
function authStatus(m,type){var el=$('#authStatus');if(!el)return;el.textContent=m;el.className='status show '+(type||'error')}
function applyLanguage(){document.documentElement.lang=state.lang==='KH'?'km':'en';$$('[data-t]').forEach(function(el){el.textContent=tr(el.getAttribute('data-t'))});var q=$('#searchInput');if(q)q.placeholder=tr('Search prompts...');$$('.lang button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-lang')===state.lang)});renderAuth();renderCart();renderPrompts();updateAuthButtons()}
function submitAuth(e){e.preventDefault();var email=($('#authEmail')||{}).value||'',pass=($('#authPassword')||{}).value||'',name=($('#authName')||{}).value||'';email=email.trim();name=name.trim();if(!email||!pass||(state.authMode==='signup'&&!name))return authStatus(state.lang==='KH'?'សូមបំពេញព័ត៌មានឲ្យគ្រប់។':'Please complete all fields.');if(pass.length<6)return authStatus(state.lang==='KH'?'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងហោចណាស់ 6 តួ។':'Password must be at least 6 characters.');var btn=$('#authSubmit');if(btn)btn.disabled=true;request(STORE,state.authMode==='signup'?'signup':'signin',{method:'POST',body:state.authMode==='signup'?{name:name,email:email,password:pass}:{email:email,password:pass}}).then(function(d){if(d.session&&d.session.access_token){state.session=d.session;state.session.email=email;save('nex_cloud_session',state.session);closeModal('#authModal');updateAuthButtons();refreshBalance();toast(state.lang==='KH'?'ចូលគណនីបានជោគជ័យ។':'Signed in successfully.')}else if(state.authMode==='signup')authStatus(state.lang==='KH'?'បានផ្ញើអ៊ីមែលបញ្ជាក់។ សូម Confirm រួចចូលគណនី។':'Confirmation email sent. Confirm it, then sign in.','success');else authStatus('Could not sign in.')}).catch(function(err){authStatus(err.message||'Request failed')}).finally(function(){if(btn)btn.disabled=false})}
function signOut(){state.session=null;save('nex_cloud_session',null);updateAuthButtons();closeModal('#authModal');toast(state.lang==='KH'?'បានចាកចេញពីគណនី។':'Signed out.')}
function mapPrompt(p){return{id:String(p.id),title:p.title||'Untitled Prompt',category:p.category||'cinematic',creator:p.creator||'Nex Prompt',model:p.model||'',price:Number(p.price||0),image:p.image_url||p.image||''}}
function loadCatalog(){request(STORE,'catalog',{timeout:9000}).then(function(d){state.catalog=(d.items||[]).map(mapPrompt);if(!state.catalog.length)state.catalog=fallback;renderPrompts()}).catch(function(){state.catalog=fallback;renderPrompts()})}
function filtered(){var q=($('#searchInput')&&$('#searchInput').value||'').toLowerCase().trim();return state.catalog.filter(function(p){return(state.filter==='all'||p.category===state.filter)&&(!q||(p.title+' '+p.creator+' '+p.model+' '+p.category).toLowerCase().indexOf(q)>=0)})}
function renderPrompts(){var g=$('#promptGrid');if(!g)return;var list=filtered();g.innerHTML=list.length?list.map(function(p){return '<article class="prompt-card" data-prompt="'+escapeHtml(p.id)+'"><div class="prompt-img" style="background-image:url(&quot;'+escapeHtml(p.image)+'&quot;)"><span class="prompt-tag">'+escapeHtml(p.category)+'</span></div><div class="prompt-body"><h3>'+escapeHtml(p.title)+'</h3><div class="prompt-meta"><span>@ '+escapeHtml(p.creator)+'</span><span class="price">$'+p.price.toFixed(2)+'</span></div><div class="prompt-meta"><span>'+escapeHtml(p.model)+'</span><span>View</span></div></div></article>'}).join(''):'<div class="empty">'+(state.lang==='KH'?'រកមិនឃើញ Prompt ទេ។':'No prompts found.')+'</div>'}
function openPrompt(id){var p=state.catalog.find(function(x){return x.id===String(id)});if(!p)return;state.selectedPrompt=p;var pv=$('#promptPreview');if(pv)pv.style.backgroundImage='url("'+p.image.replace(/"/g,'')+'")';if($('#promptTitle'))$('#promptTitle').textContent=p.title;if($('#promptDesc'))$('#promptDesc').textContent=p.category+' · '+p.model+' · @'+p.creator;if($('#promptPrice'))$('#promptPrice').textContent='$'+p.price.toFixed(2);if($('#addCartBtn'))$('#addCartBtn').textContent=state.cart.indexOf(p.id)>=0?(state.lang==='KH'?'មានក្នុងកន្ត្រក':'In Cart'):(state.lang==='KH'?'បន្ថែមទៅកន្ត្រក':'Add to Cart');openModal('#promptModal')}
function updateCartCount(){var c=$('#cartCount');if(c)c.textContent=state.cart.length}
function addCart(){if(!state.selectedPrompt)return;var id=state.selectedPrompt.id;if(state.cart.indexOf(id)<0)state.cart.push(id);save('nex_cart_cloud',state.cart);updateCartCount();toast(state.lang==='KH'?'បានបន្ថែមទៅកន្ត្រក។':'Added to cart.');openPrompt(id)}
function renderCart(){var box=$('#cartItems'),total=$('#cartTotal');if(!box||!total)return;var rows=state.cart.map(function(id){return state.catalog.find(function(p){return p.id===id})}).filter(Boolean);box.innerHTML=rows.length?rows.map(function(p){return '<div class="cart-row"><div><b>'+escapeHtml(p.title)+'</b><div class="price">$'+p.price.toFixed(2)+'</div></div><button class="remove" type="button" data-remove="'+escapeHtml(p.id)+'">Remove</button></div>'}).join(''):'<div class="empty">'+(state.lang==='KH'?'កន្ត្រកទទេ។':'Your cart is empty.')+'</div>';total.textContent='$'+rows.reduce(function(n,p){return n+p.price},0).toFixed(2)}
function ensureLogin(){if(state.session&&state.session.access_token)return true;showAuth('signup');toast(state.lang==='KH'?'សូមចុះឈ្មោះ ឬចូលគណនីជាមុន។':'Please sign up or sign in first.');return false}
function openTool(name){if(!ensureLogin())return;if($('#toolWorkspaceTitle'))$('#toolWorkspaceTitle').textContent=name;if($('#toolWorkspaceText'))$('#toolWorkspaceText').textContent=state.lang==='KH'?'Account របស់អ្នកអាចប្រើ Tool នេះបាន។ ការបង្កើត AI ពិតៗ នឹងដំណើរការបន្ទាប់ពីភ្ជាប់ AI Provider។':'Your account can access this tool. Real AI generation will work after an AI provider is connected.';openModal('#toolModal')}
function refreshBalance(){var wb=$('#walletBalance'),cp=$('#creditPageBalance');if(!(state.session&&state.session.access_token)){if(wb)wb.removeAttribute('data-balance');updateAuthButtons();return}request(CREDIT,'balance',{auth:true,timeout:8000}).then(function(d){var val=Number(d.balance||0).toLocaleString()+' Credits';if(wb){wb.setAttribute('data-balance',val);wb.textContent=val}if(cp)cp.textContent=val}).catch(function(){if(wb){wb.setAttribute('data-balance','0 Credits');wb.textContent='0 Credits'}if(cp)cp.textContent='0 Credits'})}
function renderQR(text){var box=$('#qrBox');if(!box)return;box.innerHTML='<div style="font-size:12px;line-height:1.45;color:#111;word-break:break-all;padding:14px">'+escapeHtml(text||'KHQR will appear here')+'</div>'}
function showPayment(p){closeModal('#cartModal');if($('#payTitle'))$('#payTitle').textContent=p.credits?p.credits+' Credits':(state.lang==='KH'?'ទូទាត់ Prompt':'Prompt payment');if($('#payAmount'))$('#payAmount').textContent='$'+Number(p.amount_usd||p.amount||state.creditPack&&state.creditPack.price||0).toFixed(2);if($('#payStatus'))$('#payStatus').textContent=state.lang==='KH'?'កំពុងរង់ចាំការទូទាត់…':'Waiting for payment…';renderQR(p.qr_string||p.qr||'');openModal('#paymentModal')}
function buyCredits(id,credits,price){if(!ensureLogin())return;state.creditPack={id:id,credits:credits,price:price};request(CREDIT,'create',{method:'POST',auth:true,body:{package_id:id}}).then(function(d){state.payment=Object.assign({},d.payment||{}, {type:'credit'});showPayment(state.payment)}).catch(function(err){toast(err.message||'Could not create KHQR')})}
function promptCheckout(){if(!state.cart.length)return toast(state.lang==='KH'?'កន្ត្រកទទេ។':'Your cart is empty.');request(STORE,'bakong-create',{method:'POST',body:{prompt_ids:state.cart.map(Number)}}).then(function(d){state.payment=Object.assign({},d.payment||{}, {type:'prompt'});showPayment(state.payment)}).catch(function(err){toast(err.message||'Could not create KHQR')})}
function checkPayment(){if(!state.payment||!state.payment.client_token)return toast(state.lang==='KH'?'មិនទាន់មានការទូទាត់។':'No active payment.');var isCredit=state.payment.type==='credit';request(isCredit?CREDIT:STORE,isCredit?'status':'bakong-status',{method:'POST',auth:isCredit,body:{client_token:state.payment.client_token}}).then(function(d){if(d.status==='paid'){if($('#payStatus'))$('#payStatus').textContent=state.lang==='KH'?'✓ ទូទាត់ជោគជ័យ':'✓ Payment confirmed';if(isCredit)refreshBalance();else{state.cart=[];save('nex_cart_cloud',state.cart);updateCartCount()}toast(state.lang==='KH'?'ការទូទាត់បានជោគជ័យ។':'Payment confirmed.')}else toast(state.lang==='KH'?'មិនទាន់ទទួលការទូទាត់។':'Payment not received yet.')}).catch(function(err){toast(err.message||'Could not check payment')})}
function bind(){
 document.addEventListener('click',function(e){
  var r=e.target.closest('[data-route]');if(r){e.preventDefault();route(r.getAttribute('data-route'));return}
  var cl=e.target.closest('[data-close]');if(cl){e.preventDefault();closeModal(cl.getAttribute('data-close'));return}
  var mode=e.target.closest('.auth-tab');if(mode){state.authMode=mode.getAttribute('data-mode');renderAuth();return}
  var prompt=e.target.closest('[data-prompt]');if(prompt){openPrompt(prompt.getAttribute('data-prompt'));return}
  var rem=e.target.closest('[data-remove]');if(rem){state.cart=state.cart.filter(function(x){return x!==rem.getAttribute('data-remove')});save('nex_cart_cloud',state.cart);updateCartCount();renderCart();return}
  var tool=e.target.closest('[data-tool]');if(tool){openTool(tool.getAttribute('data-tool'));return}
  var buy=e.target.closest('[data-buy]');if(buy){buyCredits(buy.getAttribute('data-buy'),Number(buy.getAttribute('data-credits')),Number(buy.getAttribute('data-price')));return}
 });
 on('#signUpBtn','click',function(){showAuth('signup')});on('#signInBtn','click',function(){showAuth('signin')});on('#authForm','submit',submitAuth);on('#signOutBtn','click',signOut);on('#addCartBtn','click',addCart);on('#cartBtn','click',function(){renderCart();openModal('#cartModal')});on('#checkoutPromptBtn','click',promptCheckout);on('#checkPaymentBtn','click',checkPayment);on('#walletBalance','click',function(){state.session&&state.session.access_token?route('credits'):showAuth('signup')});on('#creditPageBalance','click',function(){state.session&&state.session.access_token?refreshBalance():showAuth('signup')});
 on('#searchInput','input',function(){var p=$('#promptView');if(p&&!p.classList.contains('active'))route('prompt');renderPrompts()});
 on('#promptFilters','click',function(e){var b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.getAttribute('data-filter');$$('.filter').forEach(function(x){x.classList.toggle('active',x===b)});renderPrompts()});
 $$('.lang button').forEach(function(b){b.addEventListener('click',function(){state.lang=b.getAttribute('data-lang')==='KH'?'KH':'EN';localStorage.setItem('nex_prompt_lang',state.lang);applyLanguage()})});
}
function init(){window.__NEX_APP_READY=true;document.documentElement.setAttribute('data-nex-ready','1');bind();updateCartCount();applyLanguage();var h=(location.hash||'#home').slice(1);route(['home','prompt','tools','credits','how'].indexOf(h)>=0?h:'home');loadCatalog();refreshBalance()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();