(()=>{
const $=s=>document.querySelector(s), toast=m=>{const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}};
function ensureAuthFields(){const f=$('#authForm');if(!f||$('#authPassword'))return;const email=$('#authEmail');const p=document.createElement('input');p.id='authPassword';p.type='password';p.minLength=6;p.required=true;p.placeholder='Password (minimum 6 characters)';email.insertAdjacentElement('afterend',p);const submit=f.querySelector('button[type=submit]');if(submit)submit.textContent='Create account';const sign=document.createElement('button');sign.type='button';sign.id='cloudSignIn';sign.className='secondary full';sign.textContent='Sign in';submit?.insertAdjacentElement('afterend',sign)}
async function refresh(){if(!window.NexStore?.session)return;try{const me=await NexStore.me();const label=me.profile?.display_name||me.user?.email||'Account';if($('#loginBtn'))$('#loginBtn').textContent=label;if($('#footerLogin'))$('#footerLogin').textContent=label;if($('#signupSide'))$('#signupSide').textContent='Account'}catch(e){NexStore.signout()}}
window.addEventListener('DOMContentLoaded',()=>{ensureAuthFields();refresh();
const form=$('#authForm');form?.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();try{const d=await NexStore.signup($('#authName').value.trim(),$('#authEmail').value.trim(),$('#authPassword').value);if(d.session){toast('Account created and signed in');$('#authDialog')?.close();refresh()}else toast('Account created. Check your email to confirm, then sign in.')}catch(err){toast(err.message)}},true);
$('#cloudSignIn')?.addEventListener('click',async()=>{try{await NexStore.signin($('#authEmail').value.trim(),$('#authPassword').value);toast('Signed in');$('#authDialog')?.close();refresh()}catch(err){toast(err.message)}});
$('#logoutBtn')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();NexStore.signout();toast('Signed out');if($('#loginBtn'))$('#loginBtn').textContent='Login / Sign up';$('#authDialog')?.close()},true);
$('#completePurchaseBtn')?.addEventListener('click',async e=>{if(!NexStore.session)return;const local=JSON.parse(localStorage.getItem('nex_cart')||'[]').map(x=>Number(String(x).replace(/^p/,''))).filter(Number.isFinite);if(!local.length)return;e.preventDefault();e.stopImmediatePropagation();try{const r=await NexStore.checkout(local);localStorage.setItem('nex_cart','[]');if($('#cartCount'))$('#cartCount').textContent='0';toast(`Order #${r.order_id} completed`);$('#checkoutDialog')?.close()}catch(err){toast(err.message)}},true);
});
})();
