(function(){
'use strict';
var KEY='nex_prompt_demo_mode';
function $(s){return document.querySelector(s)}
function active(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');return !!(x&&x.active)}catch(e){return false}}
function isKH(){return document.documentElement.lang==='km'||localStorage.getItem('nex_prompt_lang')==='KH'}
function text(en,kh){return isKH()?kh:en}
function toast(msg){var t=$('#toast');if(!t){alert(msg);return}t.textContent=msg;t.classList.add('show');clearTimeout(window.__demoToast);window.__demoToast=setTimeout(function(){t.classList.remove('show')},2800)}
function openDialog(d){if(!d)return;try{if(!d.open)d.showModal()}catch(e){d.setAttribute('open','')}}
function closeDialog(d){if(!d)return;try{if(d.open)d.close()}catch(e){d.removeAttribute('open')}}
function injectStyles(){if($('#demoModeStyle'))return;var s=document.createElement('style');s.id='demoModeStyle';s.textContent='.demo-start-wrap{margin-top:12px;padding-top:12px;border-top:1px solid rgba(255,255,255,.08)}.demo-start-btn{width:100%;padding:12px 14px;border:1px solid #6f3154;border-radius:12px;background:#160f1d;color:#ff83bd;font-weight:900;cursor:pointer}.demo-note{margin:8px 0 0;color:#8f8494;font-size:11px;line-height:1.5;text-align:center}.demo-banner{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:9998;display:none;align-items:center;gap:10px;padding:9px 13px;border:1px solid #7a2f58;border-radius:999px;background:rgba(20,9,24,.96);box-shadow:0 12px 40px rgba(0,0,0,.35);color:#f5ddea;font-size:12px}.demo-banner.show{display:flex}.demo-badge{padding:4px 8px;border-radius:999px;background:#ff3b98;color:#fff;font-size:10px;font-weight:900}.demo-dialog{border:1px solid #65304d;border-radius:20px;background:#0f0b15;color:#fff;max-width:430px;width:calc(100% - 32px);padding:0}.demo-dialog::backdrop{background:rgba(0,0,0,.72);backdrop-filter:blur(5px)}.demo-card{padding:26px}.demo-card h2{margin:0 0 8px}.demo-card p{color:#aaa0ad;line-height:1.65}.demo-actions{display:grid;gap:9px;margin-top:18px}.demo-exit{padding:12px;border:1px solid #5d2943;border-radius:12px;background:#25101a;color:#ff9cc5;font-weight:900}.auth-group.demo-active .auth-outline{background:linear-gradient(135deg,#3a1530,#221126);color:#ff83bd}.auth-group.demo-active .auth-primary{display:none!important}';document.head.appendChild(s)}
function injectUI(){injectStyles();var form=$('#authForm');if(form&&!$('#demoStartBtn')){var box=document.createElement('div');box.className='demo-start-wrap';box.innerHTML='<button type="button" class="demo-start-btn" id="demoStartBtn">Try Demo Mode</button><p class="demo-note" id="demoStartNote">Preview AI Tools without creating a real account. Payments are disabled.</p>';form.insertAdjacentElement('afterend',box)}if(!$('#demoAccountDialog')){var d=document.createElement('dialog');d.id='demoAccountDialog';d.className='demo-dialog';d.innerHTML='<div class="demo-card"><h2 id="demoTitle">Demo Mode</h2><p id="demoText">You are previewing Nex Prompt without a verified account. Real payments, credit purchases and AI generation are disabled.</p><div class="demo-actions"><button type="button" class="btn btn-primary" id="demoToolsBtn">Open AI Tools</button><button type="button" class="demo-exit" id="demoExitBtn">Exit Demo</button></div></div>';document.body.appendChild(d)}if(!$('#demoBanner')){var b=document.createElement('div');b.id='demoBanner';b.className='demo-banner';b.innerHTML='<span class="demo-badge">DEMO</span><span id="demoBannerText">Preview only · payments disabled</span>';document.body.appendChild(b)}refreshText();updateState()}
function refreshText(){var b=$('#demoStartBtn'),n=$('#demoStartNote'),title=$('#demoTitle'),p=$('#demoText'),tools=$('#demoToolsBtn'),exit=$('#demoExitBtn'),banner=$('#demoBannerText');if(b)b.textContent=text('Try Demo Mode','សាក Demo Mode');if(n)n.textContent=text('Preview AI Tools without creating a real account. Payments are disabled.','សាកមើល AI Tools ដោយមិនបង្កើតគណនីពិត។ ការទូទាត់ត្រូវបានបិទ។');if(title)title.textContent=text('Demo Mode','Demo Mode');if(p)p.textContent=text('You are previewing Nex Prompt without a verified account. Real payments, credit purchases and AI generation are disabled.','អ្នកកំពុងសាកល្បង Nex Prompt ដោយគ្មានគណនីដែលបានបញ្ជាក់។ ការទូទាត់ ទិញ Credits និង AI Generate ពិតត្រូវបានបិទ។');if(tools)tools.textContent=text('Open AI Tools','បើក AI Tools');if(exit)exit.textContent=text('Exit Demo','ចាកចេញពី Demo');if(banner)banner.textContent=text('Preview only · payments disabled','សាកមើលតែប៉ុណ្ណោះ · ការទូទាត់ត្រូវបានបិទ')}
function updateState(){var on=active(),g=$('.auth-group'),si=$('#signInBtn'),su=$('#signUpBtn'),banner=$('#demoBanner');if(g)g.classList.toggle('demo-active',on);if(on){if(si)si.textContent='DEMO';if(su)su.style.display='none';if(banner)banner.classList.add('show')}else{if(banner)banner.classList.remove('show')}}
function startDemo(){localStorage.setItem(KEY,JSON.stringify({active:true,started_at:new Date().toISOString()}));var a=$('#authModal');if(a)closeDialog(a);updateState();toast(text('Demo mode started. AI Tools are available for preview.','បានចូល Demo Mode។ អាចសាកមើល AI Tools បាន។'));var r=document.querySelector('[data-route="tools"]');if(r)r.click()}
function exitDemo(){localStorage.removeItem(KEY);closeDialog($('#demoAccountDialog'));location.reload()}
function openDemoTool(card){var name=card.getAttribute('data-tool')||'AI Tool';var title=$('#toolWorkspaceTitle'),desc=$('#toolWorkspaceText');if(title)title.textContent=name+' · DEMO';if(desc)desc.textContent=text('Preview only. Real AI generation requires a verified account and connected AI provider.','សាកមើលតែប៉ុណ្ណោះ។ AI Generate ពិតត្រូវការគណនីដែលបានបញ្ជាក់ និងភ្ជាប់ AI Provider។');openDialog($('#toolModal'))}
function blockPayment(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();toast(text('Payments and real credits are disabled in Demo Mode.','ការទូទាត់ និង Credits ពិតត្រូវបានបិទក្នុង Demo Mode។'))}
document.addEventListener('click',function(e){var t=e.target.closest&&e.target.closest('#demoStartBtn,#demoExitBtn,#demoToolsBtn,#signInBtn,.tool-card,[data-buy],#checkoutPromptBtn,#checkPaymentBtn,#walletBalance,#creditPageBalance');if(!t)return;if(t.id==='demoStartBtn'){e.preventDefault();startDemo();return}if(t.id==='demoExitBtn'){e.preventDefault();exitDemo();return}if(t.id==='demoToolsBtn'){e.preventDefault();closeDialog($('#demoAccountDialog'));var r=document.querySelector('[data-route="tools"]');if(r)r.click();return}if(!active())return;if(t.id==='signInBtn'){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();openDialog($('#demoAccountDialog'));return}if(t.classList.contains('tool-card')){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();openDemoTool(t);return}if(t.matches('[data-buy],#checkoutPromptBtn,#checkPaymentBtn,#walletBalance,#creditPageBalance')){blockPayment(e)}},true);
document.addEventListener('click',function(e){if(e.target&&e.target.matches('[data-lang]'))setTimeout(refreshText,30)});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',injectUI);else injectUI();
})();
