const API='https://kbanmyaqodtfoqikzwou.supabase.co/functions/v1/store-api';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let catalog=[],cart=JSON.parse(localStorage.getItem('nex_cart_cloud')||'[]'),session=JSON.parse(localStorage.getItem('nex_cloud_session')||'null'),favorites=[],purchases=[],activeFilter='all',sortMode='featured';
const money=n=>'$'+Number(n).toFixed(2),saveCart=()=>localStorage.setItem('nex_cart_cloud',JSON.stringify(cart));
const CONFIRM_WAIT=60000;
let confirmTimer=null;
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2600)}
function openDialog(id){const d=document.getElementById(id);if(d&&!d.open)d.showModal()}function closeDialog(id){document.getElementById(id)?.close()}
async function api(action,{method='GET',body,query=''}={}){const h={'Content-Type':'application/json'};if(session?.access_token)h.Authorization='Bearer '+session.access_token;const r=await fetch(`${API}?action=${encodeURIComponent(action)}${query}`,{method,headers:h,body:body?JSON.stringify(body):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}
function mapPrompt(p){return{id:String(p.id),title:p.title,category:p.category,price:Number(p.price),creator:p.creator||'Nex Prompt',model:p.model||'',image:p.image_url||'',preview:p.preview_url||''}}
function updateCart(){saveCart();if($('#cartCount'))$('#cartCount').textContent=cart.length}
function filtered(){const q=($('#searchInput')?.value||'').toLowerCase().trim();let a=catalog.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&(!q||`${p.title} ${p.creator} ${p.model} ${p.category}`.toLowerCase().includes(q)));if(sortMode==='low')a.sort((x,y)=>x.price-y.price);if(sortMode==='high')a.sort((x,y)=>y.price-x.price);if(sortMode==='az')a.sort((x,y)=>x.title.localeCompare(y.title));return a}
function renderPrompts(){const g=$('#promptGrid');if(!g)return;g.innerHTML=filtered().map(p=>`<article class="prompt-card" data-id="${p.id}"><div class="prompt-image" style="--bg:url('${p.image}')"><span class="tag">${p.category}</span><button class="heart ${favorites.includes(p.id)?'active':''}" data-heart="${p.id}">${favorites.includes(p.id)?'♥':'♡'}</button><span class="mini-play">▶</span></div><div class="prompt-body"><h3>${p.title}</h3><div><span>@ ${p.creator}</span><strong>${money(p.price)}</strong></div><small>${p.model}</small></div></article>`).join('')||'<div class="empty-state">No prompts found.</div>'}
async function loadCatalog(){try{const d=await api('catalog');catalog=(d.items||[]).map(mapPrompt);renderPrompts()}catch(e){toast('Could not load cloud prompts')}}
async function syncAccount(){if(!session)return updateUser();try{const me=await api('me'),f=await api('favorites'),p=await api('purchases');favorites=(f.ids||[]).map(String);purchases=(p.items||[]).map(x=>String(x.prompt_id));session.profile=me.profile;session.email=me.user?.email;localStorage.setItem('nex_cloud_session',JSON.stringify(session));updateUser();renderPrompts()}catch(e){session=null;localStorage.removeItem('nex_cloud_session');updateUser()}}
function updateUser(){const name=session?.profile?.display_name||session?.email||'Login / Sign up';if($('#loginBtn'))$('#loginBtn').textContent=name;if($('#signupSide'))$('#signupSide').textContent=session?'Account':'Sign up now';if($('#footerLogin'))$('#footerLogin').textContent=name;if($('#logoutBtn'))$('#logoutBtn').style.display=session?'block':'none'}
function authStatus(message,type='info'){const el=$('#authStatus');if(!el)return;el.textContent=message||'';el.dataset.type=type;el.style.display=message?'block':'none'}
function setLastConfirmationNow(){localStorage.setItem('nex_confirmation_sent_at',String(Date.now()));updateConfirmCooldown()}
function confirmSecondsLeft(){const sent=Number(localStorage.getItem('nex_confirmation_sent_at')||0);return Math.max(0,Math.ceil((CONFIRM_WAIT-(Date.now()-sent))/1000))}
function updateConfirmCooldown(){const left=confirmSecondsLeft(),create=$('#authForm button[type="submit"]'),resend=$('#resendConfirmBtn');if(create){create.disabled=left>0;create.style.opacity=left>0?'.65':'1';create.textContent=left>0?`Email sent — wait ${left}s`:'Create account'}if(resend){resend.disabled=left>0;resend.style.opacity=left>0?'.55':'1';resend.textContent=left>0?`Resend available in ${left}s`:'Resend confirmation email';resend.style.display='block'}if(confirmTimer)clearInterval(confirmTimer);if(left>0)confirmTimer=setInterval(()=>{if(confirmSecondsLeft()<=0){clearInterval(confirmTimer);confirmTimer=null}updateConfirmCooldown()},1000)}
function ensurePassword(){const f=$('#authForm');if(!f||$('#authPassword'))return;const email=$('#authEmail');const wrap=document.createElement('div');wrap.className='password-wrap';wrap.style.cssText='position:relative;width:100%;margin:7px 0';const p=document.createElement('input');p.id='authPassword';p.type='password';p.minLength=6;p.required=true;p.placeholder='Password';p.autocomplete='new-password';p.style.cssText='width:100%;padding-right:52px;margin:0';const eye=document.createElement('button');eye.type='button';eye.id='togglePassword';eye.setAttribute('aria-label','Show password');eye.title='Show password';eye.innerHTML='👁';eye.style.cssText='position:absolute;right:10px;top:50%;transform:translateY(-50%);width:36px;height:36px;border:0;background:transparent;border-radius:9px;font-size:18px;display:grid;place-items:center;cursor:pointer;color:#343746';wrap.appendChild(p);wrap.appendChild(eye);email.insertAdjacentElement('afterend',wrap);eye.addEventListener('click',()=>{const show=p.type==='password';p.type=show?'text':'password';eye.innerHTML=show?'🙈':'👁';eye.setAttribute('aria-label',show?'Hide password':'Show password');eye.title=show?'Hide password':'Show password'});const submit=f.querySelector('button[type=submit]');if(submit)submit.textContent='Create account';const s=document.createElement('button');s.type='button';s.id='signInBtn';s.className='secondary full';s.textContent='Sign in';submit?.insertAdjacentElement('afterend',s);const status=document.createElement('div');status.id='authStatus';status.className='auth-status';status.style.cssText='display:none;margin-top:12px;padding:11px 13px;border-radius:10px;background:#f5f1ff;color:#6043c9;font-size:12px;line-height:1.5;text-align:left';s.insertAdjacentElement('afterend',status);const resend=document.createElement('button');resend.type='button';resend.id='resendConfirmBtn';resend.className='text-btn';resend.style.cssText='display:none;margin-top:8px';resend.textContent='Resend confirmation email';status.insertAdjacentElement('afterend',resend);updateConfirmCooldown()}
async function signup(){const name=$('#authName').value.trim(),email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!name||!email||!password)return authStatus('Please complete all fields.','error');const left=confirmSecondsLeft();if(left>0)return authStatus(`A confirmation email was already sent. Please check your inbox and wait ${left} seconds before requesting another one.`,'info');const btn=$('#authForm button[type="submit"]');if(btn){btn.disabled=true;btn.textContent='Creating account…'}authStatus('Creating your account…','info');try{const d=await api('signup',{method:'POST',body:{name,email,password}});if(d.session){session=d.session;localStorage.setItem('nex_cloud_session',JSON.stringify(session));await syncAccount();closeDialog('authDialog');toast('Account created and signed in')}else{setLastConfirmationNow();authStatus('Confirmation email sent. Open the newest email from Nex Prompt, tap Confirm, then return here and Sign in.','success')}}catch(err){const msg=String(err.message||'');if(msg.toLowerCase().includes('wait')||msg.includes('60 seconds')){setLastConfirmationNow();authStatus('A confirmation email was already requested. Check your inbox and use the newest email.','info')}else authStatus(msg,'error')}finally{updateConfirmCooldown()}}
async function resendConfirmation(){const email=$('#authEmail').value.trim();if(!email)return authStatus('Enter your email address first.','error');const left=confirmSecondsLeft();if(left>0)return authStatus(`Please wait ${left} seconds before resending.`,'info');const b=$('#resendConfirmBtn');if(b){b.disabled=true;b.textContent='Sending…'}try{await api('resend-confirmation',{method:'POST',body:{email}});setLastConfirmationNow();authStatus('New confirmation email sent. Please use only the newest email.','success')}catch(err){const msg=String(err.message||'');if(msg.toLowerCase().includes('wait')){setLastConfirmationNow();authStatus('Please wait before requesting another confirmation email.','info')}else authStatus(msg,'error')}finally{updateConfirmCooldown()}}
async function signin(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||!password)return authStatus('Enter your email and password.','error');const b=$('#signInBtn');if(b){b.disabled=true;b.textContent='Signing in…'}authStatus('Signing in…','info');try{const d=await api('signin',{method:'POST',body:{email,password}});session=d.session;localStorage.setItem('nex_cloud_session',JSON.stringify(session));await syncAccount();authStatus('');closeDialog('authDialog');toast('Signed in successfully')}catch(err){const msg=String(err.message||'');if(msg.toLowerCase().includes('not confirmed')){$('#resendConfirmBtn').style.display='block';authStatus('Your email is not confirmed yet. Open the newest confirmation email, confirm it, then Sign in again.','info')}else authStatus(msg,'error')}finally{if(b){b.disabled=false;b.textContent='Sign in'}}}
async function toggleFavorite(id){if(!session){openDialog('authDialog');return toast('Sign in first')}try{const d=await api('favorite-toggle',{method:'POST',body:{prompt_id:Number(id)}});favorites=d.favorite?[...new Set([...favorites,id])]:favorites.filter(x=>x!==id);renderPrompts();toast(d.favorite?'Saved to favorites':'Removed from favorites')}catch(e){toast(e.message)}}
async function openProduct(id){const p=catalog.find(x=>x.id===String(id));if(!p)return;let full='';const owned=purchases.includes(String(id));if(owned){try{const d=await api('prompt',{query:`&id=${encodeURIComponent(id)}`});full=d.prompt_text||''}catch{}}
$('#productDetail').innerHTML=`<div class="product-wrap"><div class="product-preview" style="background-image:url('${p.image}')"><span class="preview-badge">Image → Video</span></div><div class="product-info"><div class="tagline">${p.category} · ${p.model}</div><h2>${p.title}</h2><p>Premium image-to-video prompt by @${p.creator}.</p><div class="product-price">${money(p.price)}</div><div class="prompt-lock ${owned?'unlocked':''}">${owned?`<strong>Unlocked prompt</strong><br><code>${full}</code>`:'🔒 Full prompt is protected until purchase.'}</div><div class="product-actions">${owned?`<button class="primary" data-copy="1">Copy Prompt</button>`:`<button class="primary" data-add="${p.id}">${cart.includes(p.id)?'In Cart':'Add to Cart'}</button>`}<button class="secondary" data-fav="${p.id}">${favorites.includes(p.id)?'♥ Saved':'♡ Save'}</button></div></div></div>`;$('#productDialog').dataset.promptId=p.id;$('#productDialog').dataset.promptText=full;openDialog('productDialog')}
function renderCart(){let total=0;const items=cart.map(id=>catalog.find(p=>p.id===id)).filter(Boolean);items.forEach(p=>total+=p.price);$('#cartItems').innerHTML=items.map(p=>`<div class="cart-row"><div class="cart-thumb" style="background-image:url('${p.image}')"></div><div><h4>${p.title}</h4><small>${money(p.price)}</small></div><button class="remove-btn" data-remove="${p.id}">Remove</button></div>`).join('')||'<div class="empty-state">Your cart is empty.</div>';$('#cartTotal').textContent=money(total)}
async function renderLibrary(type){if(!session){openDialog('authDialog');return toast('Sign in first')}if(type==='favorites'){const ids=favorites;$('#libraryTitle').textContent='Favorites';$('#libraryGrid').innerHTML=ids.map(id=>catalog.find(p=>p.id===id)).filter(Boolean).map(p=>`<article class="library-card" data-library="${p.id}"><div class="img" style="background-image:url('${p.image}')"></div><div class="txt"><h4>${p.title}</h4><small>${money(p.price)}</small></div></article>`).join('')||'<div class="empty-state">No favorites yet.</div>'}else{try{const d=await api('purchases');purchases=(d.items||[]).map(x=>String(x.prompt_id));$('#libraryTitle').textContent='My Purchases';$('#libraryGrid').innerHTML=purchases.map(id=>catalog.find(p=>p.id===id)).filter(Boolean).map(p=>`<article class="library-card" data-library="${p.id}"><div class="img" style="background-image:url('${p.image}')"></div><div class="txt"><h4>${p.title}</h4><small>Unlocked · Click to open</small></div></article>`).join('')||'<div class="empty-state">No purchases yet.</div>'}catch(e){return toast(e.message)}}openDialog('libraryDialog')}
async function checkout(){if(!cart.length)return toast('Your cart is empty');if(!session){closeDialog('cartDialog');openDialog('authDialog');return toast('Sign in before checkout')}try{const d=await api('demo-checkout',{method:'POST',body:{prompt_ids:cart.map(Number)}});cart=[];updateCart();await syncAccount();closeDialog('checkoutDialog');closeDialog('cartDialog');toast(`Order #${d.order_id} completed`);renderLibrary('purchases')}catch(e){toast(e.message)}}
window.addEventListener('DOMContentLoaded',async()=>{ensurePassword();updateCart();updateUser();await loadCatalog();await syncAccount();
$('#searchInput')?.addEventListener('input',renderPrompts);$('#sortSelect')?.addEventListener('change',e=>{sortMode=e.target.value;renderPrompts()});
$('#categoryRow')?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;$$('.category').forEach(x=>x.classList.toggle('active',x===b));renderPrompts()});$$('.filter-link').forEach(a=>a.addEventListener('click',()=>{activeFilter=a.dataset.filter||'all';renderPrompts()}));
$('#promptGrid')?.addEventListener('click',e=>{const h=e.target.closest('[data-heart]');if(h){e.stopPropagation();return toggleFavorite(h.dataset.heart)}const c=e.target.closest('.prompt-card');if(c)openProduct(c.dataset.id)});
$('#productDialog')?.addEventListener('click',e=>{const a=e.target.closest('[data-add]'),f=e.target.closest('[data-fav]'),cp=e.target.closest('[data-copy]');if(a){if(!cart.includes(a.dataset.add))cart.push(a.dataset.add);updateCart();toast('Added to cart');openProduct(a.dataset.add)}if(f)toggleFavorite(f.dataset.fav).then(()=>openProduct(f.dataset.fav));if(cp){navigator.clipboard?.writeText($('#productDialog').dataset.promptText||'');toast('Prompt copied')}});
$('#cartBtn')?.addEventListener('click',()=>{renderCart();openDialog('cartDialog')});$('#mobileCart')?.addEventListener('click',()=>{renderCart();openDialog('cartDialog')});$('#cartDialog')?.addEventListener('click',e=>{const r=e.target.closest('[data-remove]');if(r){cart=cart.filter(x=>x!==r.dataset.remove);updateCart();renderCart()}});
$('#checkoutBtn')?.addEventListener('click',()=>{if(!cart.length)return toast('Your cart is empty');openDialog('checkoutDialog')});$('#completePurchaseBtn')?.addEventListener('click',checkout);
$('#authForm')?.addEventListener('submit',async e=>{e.preventDefault();await signup()});$('#signInBtn')?.addEventListener('click',signin);$('#resendConfirmBtn')?.addEventListener('click',resendConfirmation);$('#logoutBtn')?.addEventListener('click',()=>{session=null;favorites=[];purchases=[];localStorage.removeItem('nex_cloud_session');updateUser();closeDialog('authDialog');renderPrompts();toast('Signed out')});
const auth=()=>{authStatus('');updateConfirmCooldown();openDialog('authDialog')};$('#loginBtn')?.addEventListener('click',auth);$('#signupSide')?.addEventListener('click',auth);$('#footerLogin')?.addEventListener('click',auth);
$('#favoritesBtn')?.addEventListener('click',()=>renderLibrary('favorites'));$('#favoritesTopBtn')?.addEventListener('click',()=>renderLibrary('favorites'));$('#purchasesBtn')?.addEventListener('click',()=>renderLibrary('purchases'));$('#footerPurchases')?.addEventListener('click',()=>renderLibrary('purchases'));$('#mobileLibrary')?.addEventListener('click',()=>renderLibrary('purchases'));$('#libraryDialog')?.addEventListener('click',e=>{const c=e.target.closest('[data-library]');if(c){closeDialog('libraryDialog');openProduct(c.dataset.library)}});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.dataset.close)));$('#exploreBtn')?.addEventListener('click',()=>$('#popular')?.scrollIntoView({behavior:'smooth'}));$('#howBtn')?.addEventListener('click',()=>$('#how')?.scrollIntoView({behavior:'smooth'}));$('#viewAllBtn')?.addEventListener('click',()=>{activeFilter='all';if($('#searchInput'))$('#searchInput').value='';renderPrompts()});
$('#adminBtn')?.addEventListener('click',()=>toast('Cloud Admin Manager is the next step'));$('#creatorAdminBtn')?.addEventListener('click',()=>toast('Cloud Admin Manager is the next step'));$('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();toast('Message received');e.target.reset()});
});