const basePrompts=[
{id:'p1',title:'Sunset Cliff Adventure',category:'cinematic',price:2.49,creator:'Visionary',model:'Kling / Veo',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=88',prompt:'Cinematic drone push-in over a dramatic sunset cliff, warm golden-hour lighting, soft atmospheric haze, natural wind motion, subtle parallax, slow camera acceleration, realistic depth of field, 6-second shot.'},
{id:'p2',title:'Cyberpunk Night Drive',category:'sci-fi',price:2.49,creator:'NeonMaster',model:'Runway / Kling',image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1000&q=88',prompt:'Low-angle tracking shot of a futuristic sports car moving through a neon city at night, wet reflective streets, cyan and magenta signs, smooth stabilized camera, light rain, cinematic motion blur.'},
{id:'p3',title:'Floating Castle in Clouds',category:'fantasy',price:2.99,creator:'DreamCrafter',model:'Veo / Sora',image:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1000&q=88',prompt:'Slow aerial orbit around a floating fantasy castle above luminous clouds, sunrise rays, drifting mist, birds in the distance, majestic scale, gentle cinematic camera movement, detailed fantasy atmosphere.'},
{id:'p4',title:'Samurai in Red Forest',category:'cinematic',price:2.49,creator:'AI_Artist',model:'Kling / Runway',image:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1000&q=88',prompt:'A lone samurai walks slowly through a red autumn forest, leaves drifting in the air, subtle cloth motion, low-angle dolly shot, soft volumetric sunlight, calm cinematic pacing.'},
{id:'p5',title:'Ocean Wave Motion',category:'nature',price:1.99,creator:'NatureLens',model:'Veo / Pika',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=88',prompt:'A powerful ocean wave rises and curls in slow motion at golden hour, realistic foam and spray, smooth lateral camera tracking, sun reflections on water, natural physics and cinematic detail.'},
{id:'p6',title:'Luxury Watch Showcase',category:'product',price:2.99,creator:'AdCreator',model:'Kling / Runway',image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=88',prompt:'Premium black wristwatch on a dark studio pedestal, slow 180-degree product orbit, crisp specular highlights, controlled reflections, dramatic rim lighting, luxury commercial aesthetic.'},
{id:'p7',title:'Cozy Coffee Steam',category:'food',price:1.99,creator:'FoodFrame',model:'Veo / Kling',image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=88',prompt:'Close-up of a ceramic coffee cup in a cozy cafe, visible steam curling upward, slow push-in camera, warm morning window light, shallow depth of field, gentle realistic ambience.'},
{id:'p8',title:'Forest Deer Moment',category:'animals',price:2.29,creator:'WildFrame',model:'Veo / Sora',image:'https://images.unsplash.com/photo-1484406566174-9da000fda645?auto=format&fit=crop&w=1000&q=88',prompt:'A deer stands quietly in a misty forest clearing, ears and head moving naturally, soft fog drifting between trees, slow handheld-style camera approach, realistic wildlife documentary mood.'},
{id:'p9',title:'Modern Villa Tour',category:'architecture',price:2.69,creator:'ArchMotion',model:'Kling / Runway',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=88',prompt:'Smooth cinematic walkthrough toward a modern luxury villa at dusk, warm interior lighting, reflections on glass, slow gimbal movement, realistic architectural visualization.'},
{id:'p10',title:'Anime Wind Portrait',category:'anime',price:2.39,creator:'MangaMotion',model:'Kling / Pika',image:'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=88',prompt:'Anime-inspired portrait, gentle hair and clothing motion in a soft breeze, subtle blinking, slow cinematic push-in, dreamy light particles, stable facial consistency and clean motion.'},
{id:'p11',title:'Perfume Hero Commercial',category:'product',price:3.29,creator:'StudioNova',model:'Veo / Runway',image:'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1000&q=88',prompt:'Luxury perfume bottle hero shot on reflective glass, elegant slow orbit, moving light streaks, controlled mist, premium commercial lighting, macro detail and polished cinematic pacing.'},
{id:'p12',title:'Mountain Cloud Timelapse',category:'nature',price:2.19,creator:'EarthMotion',model:'Veo / Sora',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=88',prompt:'Epic mountain valley with clouds flowing between peaks, gentle timelapse feeling, stable aerial camera, realistic sunlight changes, atmospheric depth and natural landscape motion.'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let custom=load('nex_custom_prompts',[]),cart=load('nex_cart',[]),favorites=load('nex_favorites',[]),purchases=load('nex_purchases',[]),orders=load('nex_orders',[]),user=load('nex_user',null),activeFilter='all',sortMode='featured';
const allPrompts=()=>[...basePrompts,...custom],money=n=>'$'+Number(n).toFixed(2),categoryLabel=c=>({'sci-fi':'Sci-Fi',product:'Product Ads',cinematic:'Cinematic',nature:'Nature',fantasy:'Fantasy',anime:'Anime',architecture:'Architecture',animals:'Animals',food:'Food'}[c]||c);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function openDialog(id){const d=document.getElementById(id);if(d&&!d.open)d.showModal()}function closeDialog(id){document.getElementById(id)?.close()}function isPurchased(id){return purchases.includes(id)}
function filteredPrompts(){const q=($('#searchInput')?.value||'').trim().toLowerCase();let list=allPrompts().filter(p=>(activeFilter==='all'||p.category===activeFilter)&&(!q||`${p.title} ${p.category} ${p.creator} ${p.model}`.toLowerCase().includes(q)));if(sortMode==='low')list.sort((a,b)=>a.price-b.price);if(sortMode==='high')list.sort((a,b)=>b.price-a.price);if(sortMode==='az')list.sort((a,b)=>a.title.localeCompare(b.title));return list}
function renderPrompts(){const grid=$('#promptGrid');grid.innerHTML='';filteredPrompts().forEach(p=>{const a=document.createElement('article');a.className='prompt-card';a.dataset.id=p.id;a.innerHTML=`<div class="prompt-image" style="--bg:url('${p.image}')"><span class="tag">${categoryLabel(p.category)}</span><button class="heart ${favorites.includes(p.id)?'active':''}" data-heart="${p.id}">${favorites.includes(p.id)?'♥':'♡'}</button><span class="mini-play">▶</span></div><div class="prompt-body"><h3>${p.title}</h3><div><span>@ ${p.creator}</span><strong>${money(p.price)}</strong></div><small>${p.model}</small></div>`;grid.appendChild(a)});if(!grid.children.length)grid.innerHTML='<div class="empty-state">No prompts match your search.</div>'}
function setFilter(f){activeFilter=f;$$('.category').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderPrompts()}
function updateCart(){save('nex_cart',cart);$('#cartCount').textContent=cart.length}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save('nex_favorites',favorites);renderPrompts();toast(favorites.includes(id)?'Saved to favorites':'Removed from favorites')}
function openProduct(id){const p=allPrompts().find(x=>x.id===id);if(!p)return;const unlocked=isPurchased(id);$('#productDetail').innerHTML=`<div class="product-wrap"><div class="product-preview" style="background-image:url('${p.image}')"><span class="preview-badge">Image → Video</span></div><div class="product-info"><div class="tagline">${categoryLabel(p.category)} · ${p.model}</div><h2>${p.title}</h2><p>Premium prompt by @${p.creator}. Built with motion direction, camera behavior and pacing guidance for cleaner AI-video output.</p><div class="product-meta"><span>★ 4.9 rating</span><span>⚡ Instant access</span><span>▣ Copy-ready</span></div><div class="product-price">${money(p.price)}</div><div class="prompt-lock ${unlocked?'unlocked':''}">${unlocked?`<strong>Unlocked prompt</strong><br><code>${p.prompt}</code>`:'🔒 Full prompt is hidden until purchase.'}</div><div class="product-actions">${unlocked?`<button class="primary" data-copy="${p.id}">Copy Prompt</button>`:`<button class="primary" data-add="${p.id}">${cart.includes(p.id)?'In Cart':'Add to Cart'}</button>`}<button class="secondary" data-fav="${p.id}">${favorites.includes(p.id)?'♥ Saved':'♡ Save'}</button></div><div class="product-note">Use the source image as the visual reference and keep the prompt focused on motion, camera and timing.</div></div></div>`;openDialog('productDialog')}
function renderCart(){const box=$('#cartItems');box.innerHTML='';let total=0;cart.map(id=>allPrompts().find(p=>p.id===id)).filter(Boolean).forEach(p=>{total+=p.price;box.insertAdjacentHTML('beforeend',`<div class="cart-row"><div class="cart-thumb" style="background-image:url('${p.image}')"></div><div><h4>${p.title}</h4><small>${p.model} · ${money(p.price)}</small></div><button class="remove-btn" data-remove="${p.id}">Remove</button></div>`)});if(!cart.length)box.innerHTML='<div class="empty-state">Your cart is empty.</div>';$('#cartTotal').textContent=money(total)}
function renderLibrary(type){const ids=type==='favorites'?favorites:purchases;$('#libraryTitle').textContent=type==='favorites'?'Favorites':'My Purchases';const box=$('#libraryGrid');box.innerHTML='';ids.map(id=>allPrompts().find(p=>p.id===id)).filter(Boolean).forEach(p=>box.insertAdjacentHTML('beforeend',`<article class="library-card" data-library="${p.id}"><div class="img" style="background-image:url('${p.image}')"></div><div class="txt"><h4>${p.title}</h4><small>${type==='purchases'?'Unlocked · Click to open':money(p.price)}</small></div></article>`));if(!ids.length)box.innerHTML='<div class="empty-state">Nothing here yet.</div>';openDialog('libraryDialog')}
function renderOrders(){const box=$('#ordersList');box.innerHTML='';orders.slice().reverse().forEach(o=>{box.insertAdjacentHTML('beforeend',`<article class="order-card"><div><b>${o.id}</b><small>${new Date(o.createdAt).toLocaleString()}</small></div><div><span>${o.items.length} item${o.items.length===1?'':'s'}</span><strong>${money(o.total)}</strong></div><p>Payment: ${o.payment} · Status: ${o.status}</p></article>`)});if(!orders.length)box.innerHTML='<div class="empty-state">No orders yet.</div>';openDialog('ordersDialog')}
function updateUserUI(){const name=user?.name||'Login / Sign up';$('#loginBtn').textContent=name;$('#signupSide').textContent=user?'Account':'Sign up now';$('#footerLogin').textContent=user?`Account: ${user.name}`:'Login / Sign up';$('#logoutBtn').style.display=user?'block':'none';if(user){$('#authName').value=user.name||'';$('#authEmail').value=user.email||'';$('#profileName').value=user.name||'';$('#profileEmail').value=user.email||'';$('#profileBio').value=user.bio||''}}
function renderAdmin(){const box=$('#adminList');box.innerHTML='';custom.forEach(p=>box.insertAdjacentHTML('beforeend',`<div class="admin-row"><div class="admin-thumb" style="background-image:url('${p.image}')"></div><div><b>${p.title}</b><small>${categoryLabel(p.category)} · ${money(p.price)}</small></div><div class="admin-row-actions"><button class="secondary mini" data-edit-custom="${p.id}">Edit</button><button class="remove-btn" data-delete-custom="${p.id}">Delete</button></div></div>`));if(!custom.length)box.innerHTML='<p class="muted">No custom prompts yet.</p>'}
function resetAdminForm(){const f=$('#adminForm');f.reset();$('#adminEditId').value='';$('#adminSubmitBtn').textContent='Add Prompt'}
function beginEdit(id){const p=custom.find(x=>x.id===id);if(!p)return;$('#adminEditId').value=p.id;$('#adminTitle').value=p.title;$('#adminPrice').value=p.price;$('#adminCategory').value=p.category;$('#adminImage').value=p.image;$('#adminModel').value=p.model;$('#adminCreator').value=p.creator||'';$('#adminPrompt').value=p.prompt;$('#adminSubmitBtn').textContent='Save changes'}
function exportData(){const blob=new Blob([JSON.stringify({version:1,prompts:custom,user,purchases,favorites,orders},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='nex-prompt-data.json';a.click();URL.revokeObjectURL(url)}
async function importData(file){try{const data=JSON.parse(await file.text());if(Array.isArray(data.prompts)){custom=data.prompts;save('nex_custom_prompts',custom)}if(Array.isArray(data.purchases)){purchases=data.purchases;save('nex_purchases',purchases)}if(Array.isArray(data.favorites)){favorites=data.favorites;save('nex_favorites',favorites)}if(Array.isArray(data.orders)){orders=data.orders;save('nex_orders',orders)}renderAdmin();renderPrompts();toast('Data imported')}catch{toast('Invalid import file')}}
$('#searchInput')?.addEventListener('input',renderPrompts);$('#sortSelect')?.addEventListener('change',e=>{sortMode=e.target.value;renderPrompts()});
$('#categoryRow')?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b)setFilter(b.dataset.filter)});$$('.filter-link').forEach(a=>a.addEventListener('click',()=>setFilter(a.dataset.filter)));$$('[data-filter-jump]').forEach(b=>b.addEventListener('click',()=>{setFilter(b.dataset.filterJump);$('#popular').scrollIntoView({behavior:'smooth'})}));
$('#promptGrid')?.addEventListener('click',e=>{const heart=e.target.closest('[data-heart]');if(heart){e.stopPropagation();toggleFavorite(heart.dataset.heart);return}const card=e.target.closest('.prompt-card');if(card)openProduct(card.dataset.id)});
$('#productDialog')?.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),fav=e.target.closest('[data-fav]'),copy=e.target.closest('[data-copy]');if(add){if(!cart.includes(add.dataset.add))cart.push(add.dataset.add);updateCart();toast('Added to cart');openProduct(add.dataset.add)}if(fav){toggleFavorite(fav.dataset.fav);openProduct(fav.dataset.fav)}if(copy){const p=allPrompts().find(x=>x.id===copy.dataset.copy);navigator.clipboard?.writeText(p.prompt);toast('Prompt copied')}});
function openCart(){renderCart();openDialog('cartDialog')}$('#cartBtn')?.addEventListener('click',openCart);$('#mobileCart')?.addEventListener('click',openCart);
$('#cartDialog')?.addEventListener('click',e=>{const r=e.target.closest('[data-remove]');if(r){cart=cart.filter(x=>x!==r.dataset.remove);updateCart();renderCart()}});
$('#checkoutBtn')?.addEventListener('click',()=>{if(!cart.length)return toast('Your cart is empty');if(!user){closeDialog('cartDialog');openDialog('authDialog');return toast('Sign in before checkout')}$('#checkoutName').value=user.name||'';$('#checkoutEmail').value=user.email||'';closeDialog('cartDialog');openDialog('checkoutDialog')});
$$('.payment-option').forEach(b=>b.addEventListener('click',()=>{$$('.payment-option').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
$('#completePurchaseBtn')?.addEventListener('click',()=>{if(!$('#checkoutName').value.trim()||!$('#checkoutEmail').value.trim())return toast('Enter checkout name and email');const items=cart.map(id=>allPrompts().find(p=>p.id===id)).filter(Boolean);const total=items.reduce((s,p)=>s+p.price,0);const payment=$('.payment-option.active')?.dataset.payment||'qr';orders.push({id:'NEX-'+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),items:items.map(p=>p.id),total,payment,status:'Paid (demo)'});save('nex_orders',orders);purchases=[...new Set([...purchases,...cart])];save('nex_purchases',purchases);cart=[];updateCart();closeDialog('checkoutDialog');toast('Order complete — prompts unlocked');renderLibrary('purchases')});
function openAuth(){openDialog('authDialog')}$('#loginBtn')?.addEventListener('click',openAuth);$('#signupSide')?.addEventListener('click',openAuth);$('#footerLogin')?.addEventListener('click',openAuth);
$('#authForm')?.addEventListener('submit',e=>{e.preventDefault();user={...(user||{}),name:$('#authName').value.trim(),email:$('#authEmail').value.trim()};save('nex_user',user);updateUserUI();closeDialog('authDialog');toast('Account saved')});
$('#logoutBtn')?.addEventListener('click',()=>{user=null;localStorage.removeItem('nex_user');updateUserUI();closeDialog('authDialog');toast('Logged out')});
$('#profileBtn')?.addEventListener('click',()=>{if(!user)return openAuth();updateUserUI();openDialog('profileDialog')});$('#profileForm')?.addEventListener('submit',e=>{e.preventDefault();user={name:$('#profileName').value.trim(),email:$('#profileEmail').value.trim(),bio:$('#profileBio').value.trim()};save('nex_user',user);updateUserUI();closeDialog('profileDialog');toast('Profile updated')});
$('#purchasesBtn')?.addEventListener('click',()=>renderLibrary('purchases'));$('#footerPurchases')?.addEventListener('click',()=>renderLibrary('purchases'));$('#mobileLibrary')?.addEventListener('click',()=>renderLibrary('purchases'));$('#favoritesBtn')?.addEventListener('click',()=>renderLibrary('favorites'));$('#favoritesTopBtn')?.addEventListener('click',()=>renderLibrary('favorites'));$('#ordersBtn')?.addEventListener('click',renderOrders);$('#footerOrders')?.addEventListener('click',renderOrders);
$('#libraryDialog')?.addEventListener('click',e=>{const c=e.target.closest('[data-library]');if(c){closeDialog('libraryDialog');openProduct(c.dataset.library)}});
function openAdmin(){renderAdmin();openDialog('adminDialog')}$('#adminBtn')?.addEventListener('click',openAdmin);$('#creatorAdminBtn')?.addEventListener('click',openAdmin);
$('#adminList')?.addEventListener('click',e=>{const del=e.target.closest('[data-delete-custom]'),edit=e.target.closest('[data-edit-custom]');if(del){custom=custom.filter(p=>p.id!==del.dataset.deleteCustom);save('nex_custom_prompts',custom);renderAdmin();renderPrompts();toast('Prompt removed')}if(edit)beginEdit(edit.dataset.editCustom)});
$('#adminForm')?.addEventListener('submit',e=>{e.preventDefault();const id=$('#adminEditId').value;const p={id:id||'custom-'+Date.now(),title:$('#adminTitle').value.trim(),price:Number($('#adminPrice').value),category:$('#adminCategory').value,image:$('#adminImage').value.trim(),model:$('#adminModel').value.trim(),creator:$('#adminCreator').value.trim()||user?.name||'Nex Prompt',prompt:$('#adminPrompt').value.trim()};if(id)custom=custom.map(x=>x.id===id?p:x);else custom.push(p);save('nex_custom_prompts',custom);resetAdminForm();renderAdmin();renderPrompts();toast(id?'Prompt updated':'Prompt added')});
$('#adminCancelEdit')?.addEventListener('click',resetAdminForm);$('#exportBtn')?.addEventListener('click',exportData);$('#importBtn')?.addEventListener('click',()=>$('#importFile').click());$('#importFile')?.addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''});
$('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();e.target.reset();toast('Message saved in demo mode')});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.dataset.close)));$('#viewAllBtn')?.addEventListener('click',()=>{setFilter('all');$('#searchInput').value='';renderPrompts()});$('#exploreBtn')?.addEventListener('click',()=>$('#popular').scrollIntoView({behavior:'smooth'}));$('#howBtn')?.addEventListener('click',()=>$('#how').scrollIntoView({behavior:'smooth'}));
$('#mobileMenuBtn')?.addEventListener('click',()=>$('#sidebar').classList.toggle('mobile-open'));$$('.sidebar a,.sidebar button').forEach(el=>el.addEventListener('click',()=>$('#sidebar').classList.remove('mobile-open')));
updateCart();updateUserUI();renderPrompts();